#!/usr/bin/env bash
# @description Regenerate $HOME/.foreman/env.sh for non-interactive lane shells.
#
# Lanes do not source ~/.bashrc, so PATH fixes that live only in a profile never
# reach them. This writer emits a small POSIX-sourceable env file that lanes can
# source explicitly. It only ever writes env.sh under $HOME/.foreman/; it does
# not clobber other files in that directory.
#
# Usage:
#   bash env/foreman-env-write.sh
#
# The generated file prepends (when present) $HOME/.local/bin then /usr/local/bin,
# guards against duplicate PATH entries on re-source, and never embeds
# fnm_multishells paths (those are per-shell and invalid elsewhere).

set -euo pipefail

FOREMAN_DIR="${HOME}/.foreman"
ENV_FILE="${FOREMAN_DIR}/env.sh"

mkdir -p "${FOREMAN_DIR}"

# Write atomically via temp file in the same directory, then mv.
tmp="${ENV_FILE}.tmp.$$"
trap 'rm -f "${tmp}"' EXIT

cat > "${tmp}" <<'EOF'
# Generated by env/foreman-env-write.sh — do not hand-edit.
# Regenerate with: bash env/foreman-env-write.sh
#
# POSIX-sourceable. Side effect: export PATH only.
# Prepends (if present, without duplicating): $HOME/.local/bin, then /usr/local/bin.

# Prepend lower-priority first so the final front-of-PATH order is:
#   $HOME/.local/bin : /usr/local/bin : <existing PATH>
if [ -d /usr/local/bin ]; then
  case ":${PATH}:" in
    *:"/usr/local/bin":*) ;;
    *) PATH="/usr/local/bin:${PATH}" ;;
  esac
fi

if [ -d "${HOME}/.local/bin" ]; then
  case ":${PATH}:" in
    *:"${HOME}/.local/bin":*) ;;
    *) PATH="${HOME}/.local/bin:${PATH}" ;;
  esac
fi

export PATH
EOF

mv -f "${tmp}" "${ENV_FILE}"
trap - EXIT

# Ensure the generated file is readable (not executable required for sourcing).
chmod 644 "${ENV_FILE}"
