/**
 * @foreman/orchestration — queue admission (Sprint 3 R1), attempt-bound
 * round transaction core (Sprint 3 R2 / R3), and typed vendor preflight
 * (Sprint 3 R4A). Remaining orchestration ports and shell adapter seams stay
 * open.
 */

export {
  EXIT_OK,
  EXIT_FAIL,
  EXIT_CONFIG,
  EXIT_MISSING_CLI,
  FIXED_GROUPS,
  GROUP_RE,
  TASK_ID_RE,
  pwshQuote,
  posixQuote,
  isWindowsPueuePath,
  parseShellCommandOverride,
  quoteForShell,
  isPreAcceptRefusal,
  isEmptyAdmissionStdout,
  isRetryablePreAcceptFailure,
  parseTaskId,
  ensureGroup,
  cmdEnsure,
  cmdAdd,
  cmdStatus,
  cmdKill,
  resolvePueueClient,
  resolvePueued,
  readShellCommandOverride,
  type EnsureOptions,
  type QuoteResult,
  type ShellDialect,
  type ShellCommandParse,
  type ShellOverrideRead,
} from "./queue-admission.js";

export {
  parseQueueArgv,
  stripNodeArgv,
  runQueueCli,
  type ParsedCommand,
} from "./queue-cli.js";

export {
  ProcessExec,
  ProcessFailure,
  Sleeper,
  PathLookup,
  BoundedFs,
  EnvVars,
  MAX_CAPTURE_BYTES,
  MAX_CONFIG_BYTES,
  OWNED_CHILD_CANCEL_WAIT_MS,
  TIMEOUT_STATUS_PROBE_MS,
  TIMEOUT_QUEUE_OP_MS,
  liveQueueServices,
  liveProcessExec,
  terminateOwnedChild,
  readFileBoundedSync,
  type BoundedReadResult,
  type CapturedProcessResult,
  type ProcessFailureReason,
  type QueueIo,
  type RunCapturedOptions,
  type RunForegroundOptions,
  type RunIgnoredStdioOptions,
} from "./queue-services.js";

// --- Sprint 3 R2: attempt-bound round transaction core ---

export {
  MAX_COMMAND_ARGV_ENTRIES,
  MAX_COMMAND_ARG_BYTES,
  MAX_COMMAND_ARGV_TOTAL_BYTES,
  MAX_GATE_COMMAND_BYTES,
  MAX_REPORT_PATH_BYTES,
  MAX_REPORT_CONTENT_BYTES,
  ROUND_CONTRACT_FAILURE_BRAND,
  roundContractFailure,
  isRoundContractFailure,
  presentReportSnapshot,
  absentReportSnapshot,
  decodeReportSnapshotV1,
  isIncompleteReason,
  isExitCode,
  decodeCommandArgv,
  decodeRoundRequestV1,
  decodeRoundPlanV1,
  attemptIdentityFromPlan,
  decodeAttemptIdentityValue,
  decodeRoundOutcomeV1,
  decodeCheckpointIdentityV1,
  makeCheckpointIdentity,
  attemptIdentitiesEqual,
  roundOutcomesEqual,
  snapshotsEqual,
  utf8ByteLength,
  type RoundContractFailureReason,
  type RoundContractFailure,
  type ReportSnapshotPresentV1,
  type ReportSnapshotV1,
  type IncompleteReason,
  type RoundPlanV1,
  type RoundRequestV1,
  type RoundOutcomeCompletedV1,
  type RoundOutcomeIncompleteV1,
  type RoundOutcomeV1,
  type CheckpointIdentityV1,
} from "./round-contract.js";

export {
  isReportFresh,
  decideRoundOutcome,
  isPresentNonempty,
  type ReportReadFailureReason,
  type ReportReadResult,
  type OutcomeDecisionInput,
} from "./report-freshness.js";

export {
  initialRoundReducerState,
  reduceRoundEvent,
  recoverRoundAttempt,
  type RoundReducerPhase,
  type RoundReducerState,
  type RoundTransitionRejectionReason,
  type RoundTransitionResult,
  type RecoveryInvalidReason,
  type RoundRecoveryResult,
} from "./round-reducer.js";

export {
  RoundBoundaryFailure,
  AttemptAllocator,
  RoundEventSink,
  ReportSnapshotReader,
  ImplementationCommand,
  CheckpointCapture,
  GateCommand,
  runRoundTransaction,
  type RoundBoundaryFailureReason,
  type RoundEventDraft,
  type RoundTransactionServices,
} from "./round-transaction.js";

// --- Sprint 3 R3: live round runtime ---

export {
  makeLiveRoundServices,
  liveReportRead,
  buildGateProcessVector,
  sanitizedCheckpointEnv,
  parseCheckpointCommit,
  CHECKPOINT_OUTPUT_BOUND_BYTES,
  type LiveRoundContext,
  type GateProcessVector,
  type ReportReadSeams,
} from "./round-live-services.js";

export {
  parseRoundArgv,
  stripRoundNodeArgv,
  preflightRoundParsed,
  isEqualOrDescendant,
  runRoundCli,
  EXIT_COMPLETED,
  EXIT_INCOMPLETE_OR_DEFECT,
  EXIT_INVALID_ARGUMENTS,
  EXIT_BOUNDARY_FAILURE,
  MSG_INVALID_ARGUMENTS,
  MSG_BOUNDARY_FAILURE,
  MSG_INTERNAL_FAILURE,
  type ParsedRoundArgv,
  type RoundPreflightResult,
  type RoundCliIo,
  type RoundCliEnv,
} from "./round-cli.js";

// --- Sprint 3 R4A: typed vendor preflight ---

export {
  VENDOR_IDS,
  VENDOR_EVIDENCE_CLASSES,
  DISCOVERABLE_VALUES,
  AUTH_VALUES,
  CURRENCY_VALUES,
  PROBE_KINDS,
  PROBE_OUTCOMES,
  REMEDIATION_KINDS,
  MAX_REASON_BYTES,
  MAX_INSTRUCTION_BYTES,
  MAX_VERSION_BYTES,
  MAX_PATH_BYTES,
  MAX_PROBE_ARGV_ENTRIES,
  MAX_PROBE_ARG_BYTES,
  MAX_PROBE_ARGV_TOTAL_BYTES,
  MAX_PROBES,
  VENDOR_PREFLIGHT_CONTRACT_FAILURE_BRAND,
  vendorPreflightContractFailure,
  isVendorPreflightContractFailure,
  isStrictUtcRfc3339,
  checkRecordConsistency,
  validateProbeArgv,
  decodeVendorPreflightRecordV1,
  recordIsFullyReady,
  type VendorId,
  type VendorEvidenceClass,
  type DiscoverableValue,
  type AuthValue,
  type CurrencyValue,
  type ProbeKind,
  type ProbeOutcome,
  type RemediationKind,
  type VendorPreflightContractFailureReason,
  type VendorPreflightContractFailure,
  type VendorFactV1,
  type ProbeRecordV1,
  type RemediationV1,
  type VendorPreflightRecordV1,
} from "./vendor-preflight-contract.js";

export {
  decodeVendorCapabilityV1,
  decodeVendorCapabilityTableV1,
  capabilityTableToCanonicalJson,
  capabilityTableDigest,
  findCapability,
  parseVendorCapabilitiesFromToml,
  FORBIDDEN_MUTATING_UPDATE_ARGV_TAILS,
  GROK_NON_MUTATING_UPDATE_CHECK_ARGV,
  argvContainsMutatingUpdate,
  type VendorCapabilityV1,
  type VendorCapabilityTableV1,
  type CapabilityParseFailure,
} from "./vendor-preflight-manifest.js";

export {
  parseFirstSemVer,
  compareSemVer,
  formatSemVer,
  classifyCurrency,
  classifyClaudeAuth,
  classifyCodexAuth,
  classifyGrokAuth,
  classifyAuthForVendor,
  decideRemediation,
  makeFact,
  buildMissingRecord,
  buildDiscoveredRecord,
  processFailureToProbeOutcome,
  type SemVer,
  type CurrencyClassification,
  type AuthClassification,
  type RemediationDecision,
} from "./vendor-preflight.js";

export {
  PREFLIGHT_PROBE_TIMEOUT_MS,
  PREFLIGHT_PROBE_OUTPUT_BOUND_BYTES,
  VendorPreflightFailure,
  PreflightClock,
  livePreflightClock,
  VendorPreflight,
  inspectVendor,
  liveVendorPreflight,
  liveVendorPreflightLayer,
  type VendorPreflightFailureReason,
} from "./vendor-preflight-live.js";

export {
  EXIT_READY as PREFLIGHT_EXIT_READY,
  EXIT_NOT_READY as PREFLIGHT_EXIT_NOT_READY,
  EXIT_INVALID_ARGUMENTS as PREFLIGHT_EXIT_INVALID_ARGUMENTS,
  EXIT_BOUNDARY_FAILURE as PREFLIGHT_EXIT_BOUNDARY_FAILURE,
  MSG_INVALID_ARGUMENTS as PREFLIGHT_MSG_INVALID_ARGUMENTS,
  MSG_UNCONFIGURED_VENDOR as PREFLIGHT_MSG_UNCONFIGURED_VENDOR,
  MSG_BOUNDARY_FAILURE as PREFLIGHT_MSG_BOUNDARY_FAILURE,
  MSG_INTERNAL_FAILURE as PREFLIGHT_MSG_INTERNAL_FAILURE,
  stripPreflightNodeArgv,
  parsePreflightArgv,
  runVendorPreflightCli,
  type PreflightCliIo,
  type ParsedPreflightArgv,
  type PreflightCliRuntime,
  type PreflightCliEnv,
} from "./vendor-preflight-cli.js";

export {
  tryGetEmbeddedCapabilityTable,
  getEmbeddedCapabilityDigest,
  loadCapabilityTableFromTomlText,
} from "./vendor-preflight-embedded.js";
