import {test} from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdirSync,writeFileSync,statSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {Effect,Stream} from 'effect';
import {validateDataSchema,createAuthoringSnapshotV1,checkPel,type PelDataValue} from '@foreman/pel';
import type {ProviderRequestV1,ProviderIdentityV1,ProviderTransport} from '@foreman/providers';
import {pelHostFixture} from './pel-host-test-fixture.js';
import {PelRuntime,type HostContextV1} from './pel-run-contract.js';
import {makePelTaskHandler,type PelTaskPorts} from './pel-host-task.js';
import {executeHostEffect} from './pel-effects.js';
import {pelHash,pelFailure,readPelRecords,replayPelRun} from './pel-journal.js';
import {completePelHostProvider,recoverPelHostOperation} from './pel-host-recovery.js';
import {decodeCandidateRefV1,decodeImplementationReceiptV1,type ImplementationReceiptV1} from './pel-host-contract.js';
import {foremanDataSchemasV1,createDefaultAuthoringSnapshotV1} from './pel-host-descriptors.js';
const text=(value:string):PelDataValue=>({tag:'string',value});
const assoc=(fields:Record<string,PelDataValue>):PelDataValue=>({tag:'list',items:Object.entries(fields).map(([key,value])=>({tag:'pair',key,value}))});
const report=assoc({summary:text('untrusted report'),claimedPaths:{tag:'list',items:[text('invented.ts')]},findings:{tag:'list',items:[]}});
const field=(value:PelDataValue,key:string)=>value.tag==='list'?value.items.find(x=>x.tag==='pair'&&x.key===key):undefined;
for(const mode of ['change','no-change','out-of-scope','invalid-report','wrong-identity','completion-interrupted','missing-artifact','alternate-role','api-task'] as const)test(`task ${mode} uses original native selection, host-observed candidate, one reservation and recovery`,async()=>{
 const baseSnapshot=createDefaultAuthoringSnapshotV1(),reviewer=baseSnapshot.roleBindings['role:reviewer']!,changed=createAuthoringSnapshotV1({...baseSnapshot,roleBindings:{...baseSnapshot.roleBindings,'role:implementer':{...reviewer,controls:{...reviewer.controls,effort:'high'},credentialProfileRef:'account:test'}}});assert.equal(changed.ok,true);
 const source=mode==='api-task'?'(fm/task :id "implement" :model "grok-4.6" :transport "xai-responses" :input "artifact:approved-spec" :output "schema:candidate-v1")':'(fm/task :id "implement" :model "role:implementer" :input "artifact:approved-spec" :output "schema:candidate-v1")';
 const f=pelHostFixture(source,{snapshot:mode==='alternate-role'&&changed.ok?changed.value:baseSnapshot});
 try{await Effect.runPromise(f.provide(Effect.gen(function*(){
  const fixture=yield* f.setup,repo=join(f.root,'repo');mkdirSync(repo);mkdirSync(join(repo,'src'));
  const git=(...args:string[])=>execFileSync('git',args,{cwd:repo,encoding:'utf8'}).trim();git('init','-q');git('config','user.email','fixture@invalid');git('config','user.name','fixture');writeFileSync(join(repo,'src/main.ts'),'before\n');git('add','.');git('commit','-qm','base');
  const common=join(repo,'.git'),info=statSync(repo),gi=statSync(common),repository={gitCommonDir:common,identitySha256:pelHash({gitCommonDir:common,directoryIdentity:`${gi.dev}:${gi.ino}`})},base=git('rev-parse','HEAD');
  const workspace={...fixture.context.workspace,repository,canonicalRoot:repo,directoryIdentity:`${info.dev}:${info.ino}`,immutableBase:base,writablePaths:['src']};
  const context:HostContextV1={...fixture.context,binding:{...fixture.context.binding,repository},workspace,project:{...fixture.context.project,repository,taskActions:{implement:'implement'},workspaces:{...fixture.context.project.workspaces,grants:[workspace]}}};
  let starts=0,registrations=0;const receipts:ImplementationReceiptV1[]=[],requests:ProviderRequestV1[]=[];
  const identity:ProviderIdentityV1={kind:'native',provider:'xai',profileId:'grok-4.6',transportId:'grok-acp',credentialProfileRef:'credential:default',protocolVersion:'fixture-v1',sessionId:'session'};
  const ports:PelTaskPorts={resolveInput:()=>Effect.succeed([{id:'approved-spec',contentRef:'artifact:approved-spec',sha256:pelHash({spec:'bounded'}),content:{spec:'bounded'}}]),nativePolicy:()=>Effect.succeed({permissionGrantIds:['grant'],hostPermissionPortRef:'permissions'}),transportVersion:()=>Effect.succeed('fixture-v1'),actionCandidate:()=>Effect.succeed({commit:base,tree:git('rev-parse','HEAD^{tree}'),candidateSha256:pelHash(base)}),recordImplementation:(candidate,candidateRef,receipt)=>Effect.sync(()=>{registrations++;receipts.push(receipt);if(mode==='change'||mode==='completion-interrupted'||mode==='missing-artifact'||mode==='alternate-role'){assert.ok(candidateRef);assert.ok(candidate);assert.equal(decodeCandidateRefV1(candidate).ok,true);assert.equal(git('show',`${candidate.commit}:src/main.ts`),'after');}else assert.equal(candidate,null);})};
  const handler=makePelTaskHandler(ports),runtime=fixture.runtime;
  const transport:ProviderTransport={id:'grok-acp',version:'fixture-v1',start:request=>Effect.sync(()=>{starts++;requests.push(request);if(mode==='change'||mode==='completion-interrupted'||mode==='missing-artifact'||mode==='alternate-role')writeFileSync(join(repo,'src/main.ts'),'after\n');if(mode==='out-of-scope')writeFileSync(join(repo,'forbidden.ts'),'forbidden');const actualIdentity={...identity,provider:mode==='alternate-role'?'openai':'xai',profileId:request.profileId,transportId:request.transportId,credentialProfileRef:request.credentialProfileRef,...(mode==='wrong-identity'?{provider:'openai'}:{})};return Stream.make({schemaVersion:1,effectId:request.effectId,providerIdentity:actualIdentity,payload:{type:'completed',result:{schemaId:request.outputSchema.id,value:mode==='invalid-report'?text('bad'):report,json:mode==='invalid-report'?'bad':{summary:'untrusted report',claimedPaths:['invented.ts'],findings:[]},schemaSha256:pelHash(request.outputSchema.content),byteLength:100}}} as const);}),probe:()=>Effect.die('unexpected probe'),resume:()=>Effect.die('provider must not resume'),cancel:()=>Effect.die('unexpected cancel'),observe:()=>Effect.die('unexpected observe'),sendToolResult:()=>Effect.die('unexpected tool')};
  Object.assign(runtime,{handlers:new Map([['fm/task',handler]]),providers:{...runtime.providers,resolve:()=>Effect.succeed({transport})}});
  if(mode==='completion-interrupted'){const artifacts=runtime.artifacts;let injected=false;Object.assign(runtime,{artifacts:{...artifacts,put:(...args:Parameters<typeof artifacts.put>)=>{if(!injected&&Buffer.from(args[1]).toString('utf8').includes('\"stage\":\"task-completed\"')){injected=true;return Effect.fail(pelFailure('journal-write-failed','Injected crash before host completion record.'));}return artifacts.put(...args);}}});}
  const index=readFileSync(join(common,'index'));
  yield* Effect.gen(function*(){
   if(mode==='completion-interrupted'){const interrupted=yield* executeHostEffect(fixture.request,context).pipe(Effect.either);assert.equal(interrupted._tag,'Left');assert.equal(starts,1);assert.equal(registrations,0);const recovered=yield* recoverPelHostOperation(context);assert.ok(recovered);assert.equal(recovered.kind,'settled');if(recovered.kind==='settled')assert.equal(recovered.outcome.tag,'success');assert.equal(starts,1);assert.equal(registrations,1);assert.equal(git('rev-parse','HEAD'),base);assert.deepEqual(readFileSync(join(common,'index')),index);assert.equal((yield* fixture.ledger.status(context.binding.contractId)).counts.implement,1);return;}
   const outcome=yield* executeHostEffect(fixture.request,context);if(mode==='api-task'){assert.equal(outcome.kind,'settled');if(outcome.kind==='settled')assert.equal(outcome.receipt.outcome.tag,'failure');assert.equal(starts,0);assert.equal((yield* fixture.ledger.status(context.binding.contractId)).counts.implement,0);return;}assert.equal(outcome.kind,'settled');if(outcome.kind!=='settled')throw Error('Expected settled');
   const failure=['out-of-scope','invalid-report','wrong-identity'].includes(mode);assert.equal(outcome.receipt.outcome.tag,failure?'failure':'success',JSON.stringify(outcome));assert.equal(starts,1,JSON.stringify(outcome));assert.equal(registrations,failure?0:1);
   assert.equal(requests[0]!.toolPolicy.mode,'native-coding');assert.equal(requests[0]!.outputSchema.id,'schema:candidate-v1');assert.equal(requests[0]!.limits.deadline,context.binding.limits.deadline);if(mode==='alternate-role'){assert.equal(requests[0]!.profileId,'gpt-5.6-sol');assert.equal(requests[0]!.transportId,'codex-app-server');assert.equal(requests[0]!.credentialProfileRef,'account:test');assert.equal(requests[0]!.controls.effort,'high');}
   if(outcome.receipt.outcome.tag==='success'){assert.equal(validateDataSchema(outcome.receipt.outcome.value,foremanDataSchemasV1['schema:task-result-v1']!),true);assert.deepEqual(field(outcome.receipt.outcome.value,'status'),{tag:'pair',key:'status',value:text(mode==='change'||mode==='missing-artifact'||mode==='alternate-role'?'candidate-ready':'no-change')});assert.equal(decodeImplementationReceiptV1(receipts[0]).ok,true);
    const recovered=yield* completePelHostProvider(context,{value:report,identity:{...identity,credentialProfileRef:requests[0]!.credentialProfileRef}});assert.equal(recovered.kind,'settled');assert.equal(starts,1);assert.equal(registrations,2);assert.equal(pelHash(receipts[1]),pelHash(receipts[0]));
    if(mode==='missing-artifact'){const original=runtime.artifacts;Object.assign(runtime,{artifacts:{...original,get:(...args:Parameters<typeof original.get>)=>args[1].sha256===receipts[0]!.reportRef.sha256?Effect.fail(pelFailure('binding-mismatch','Injected missing report artifact.')):original.get(...args)}});const missing=yield* completePelHostProvider(context,{value:report,identity:{...identity,credentialProfileRef:requests[0]!.credentialProfileRef}}).pipe(Effect.either);assert.equal(missing._tag,'Left');assert.equal(registrations,2);assert.equal(starts,1);}
   }
   assert.equal(git('rev-parse','HEAD'),base);assert.deepEqual(readFileSync(join(common,'index')),index);const ledger=yield* fixture.ledger.status(context.binding.contractId);assert.equal(ledger.counts.implement,1);const replay=replayPelRun(yield* readPelRecords(context.binding.runId));assert.equal(replay.ok,true);
  }).pipe(Effect.provideService(PelRuntime,runtime));
 })));}finally{f.close();}
});

test('T-M5-016 conflicting role and transport are rejected during checking without a provider fallback',()=>{const result=checkPel({source:Buffer.from('(fm/task :id "implement" :model "role:implementer" :transport "codex-app-server" :input "artifact:approved-spec" :output "schema:candidate-v1")'),snapshot:createDefaultAuthoringSnapshotV1()});assert.equal(result.tag,'invalid');});
