import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Effect, Stream } from 'effect';
import { canonicalize, sha256Hex } from '@foreman/core';
import { RunJournal } from '@foreman/event-log';
import { decodeReleaseAuthorityFileV1, type ReleaseEvidenceBundleV1 } from '@foreman/policy';
import type { PelDataValue } from '@foreman/pel';
import type { ProviderTransport } from '@foreman/providers';
import { pelHostFixture } from './pel-host-test-fixture.js';
import { deriveExecutionContractFamilyV2 } from './execution-contract.js';
import { PelRuntime, decodePelActionAuthorityV1, type HostContextV1, type PelReservationTokenV1 } from './pel-run-contract.js';
import { makePelHostLibraryServices } from './pel-host-library.js';
import { makePelReviewHandler } from './pel-host-review.js';
import { recordPelReleaseMilestone } from './pel-host-milestone.js';
import { completePelHostProvider } from './pel-host-recovery.js';
import { executeHostEffect } from './pel-effects.js';
import { pelHash, readPelRecords, replayPelRun, stablePelEffectIdentity, stablePelReservationId } from './pel-journal.js';
import { liveProcessExec, ProcessExec } from './queue-services.js';
import { decodeCandidateRefV1, decodeVerificationReceiptV1, type CandidateRefV1, type VerificationReceiptV1 } from './pel-host-contract.js';

const rows = [['v040-t2-project-registry', 'project-registry', []], ['v040-t3-memory-index', 'external-memory-index', ['v040-t2-project-registry']], ['v040-t4-appliance', 'hermetic-foreman-appliance', []], ['v040-t5-graphify', 'knowledge-plane-refresh', []], ['v040-t6-work-dag', 'work-dag-projection', ['v040-t5-graphify']], ['v040-t7-context', 'graph-context-builder', ['v040-t6-work-dag']], ['v040-t8-evaluation', 'graph-eval-falsification', ['v040-t3-memory-index', 'v040-t4-appliance', 'v040-t7-context']], ['v040-t9-release', 'v040-release-program', ['v040-t2-project-registry', 'v040-t3-memory-index', 'v040-t4-appliance', 'v040-t5-graphify', 'v040-t6-work-dag', 'v040-t7-context', 'v040-t8-evaluation']]] as const;
const str = (value: string): PelDataValue => ({ tag: 'string', value });
const assoc = (fields: Record<string, PelDataValue>): PelDataValue => ({ tag: 'list', items: Object.entries(fields).map(([key, value]) => ({ tag: 'pair', key, value })) });

for (const variant of ['two-retries', 'missing-grant', 'wrong-prior', 'wrong-origin'] as const) test(`V2 review retry keeps its durable audit origin: ${variant}`, async () => {
    const f = pelHostFixture('(fm/review :id "review" :model "role:reviewer" :input "artifact:approved-spec" :policy "independent-review")');
    try { await Effect.runPromise(f.provide(Effect.gen(function* () {
        const fixture = yield* f.setup, { put, runtime, ledger, now } = fixture, journal = yield* RunJournal, processExec = yield* ProcessExec;
        const at = new Date(now).toISOString().replace('.000Z', 'Z'), bytes = (value: unknown) => Buffer.from(canonicalize(value) + '\n');
        const source = { schema: 'foreman.execution-family-source.v1', program: 'v040', familyId: 'v040-release-20260822-f1', children: rows.map(([childId, packageId, dependencyChildIds], index) => ({ schema: 'foreman.execution-child-brief.v1', childId, packageId, dependencyChildIds, tranche: index + 2, objective: 'Review retry fixture', acceptance: ['Exact origin survives retries'], allowedPaths: ['src/**'] })) };
        const derived = deriveExecutionContractFamilyV2({ rootContractId: fixture.contract.contractId, rootContractSha256: fixture.context.binding.contractSha256, track1Commit: fixture.contract.baseCommit, track1Tree: 'b'.repeat(40), sourceBytes: bytes(source), createdAt: at }); assert.equal(derived._tag, 'Valid'); if (derived._tag !== 'Valid') throw Error(JSON.stringify(derived));
        const common = { rootContractId: fixture.contract.contractId, rootContractSha256: fixture.context.binding.contractSha256, familySha256: derived.familySha256 }, familyAuthority = { ...common, sourceSha256: sha256Hex(bytes(source)), auditReceiptSha256: 'a'.repeat(64), userReceiptSha256: 'b'.repeat(64) };
        yield* ledger.registerFamilyAuthority({ ...familyAuthority, manifest: derived.manifest, registeredAt: at }); yield* ledger.activateFamily({ ...familyAuthority, activatedAt: at });
        const child = derived.manifest.children[0]!, identity = { commit: 'c'.repeat(40), tree: 'd'.repeat(40), candidateSha256: sha256Hex('c'.repeat(40)) }, reportRef = yield* put({ checked: true }), taskPlanSha256 = 'c'.repeat(64);
        const baseCandidate = { commit: fixture.contract.baseCommit, tree: 'b'.repeat(40), candidateSha256: sha256Hex(fixture.contract.baseCommit) };
        for (const action of ['implement', 'verify'] as const) {
            const candidate = action === 'implement' ? baseCandidate : identity;
            const design = { schema: 'foreman.design-approval.v1' as const, program: 'v040' as const, packageId: child.packageId, designCommit: baseCandidate.commit, designTree: baseCandidate.tree, approvedOpenSpecSha256: reportRef.sha256, taskPlanSha256, approvalStatementSha256: reportRef.sha256, issuedAt: at };
            const bundle: ReleaseEvidenceBundleV1 = { schema: 'foreman.release-evidence-bundle.v1', program: 'v040', ...common, childId: child.childId, packageId: child.packageId, action, candidate, taskPlanSha256, receipts: [design], issuedAt: at };
            const bundleBytes = bytes(bundle); assert.equal(decodeReleaseAuthorityFileV1(bundleBytes)._tag, 'Valid');
            const ref = yield* runtime.artifacts.put(fixture.context.binding.runId, bundleBytes, 65536, 'ordinary');
            yield* ledger.registerChildAuthority({ ...common, childId: child.childId, action, effectiveAction: action, candidate, priorReservationId: null, originReservationId: null, taskPlanSha256, bundleSha256: ref.sha256, receiptSchemas: [design.schema], receiptSha256s: [sha256Hex(bytes(design))], evaluationManifestSha256: null, registeredAt: at });
            const reservationId = `fixture-${action}`, reserved = yield* ledger.executeChild({ ...common, childId: child.childId, operation: { _tag: 'ReserveAction', reservationId, reservationAction: action, effectiveAction: action, originReservationId: reservationId, candidate, taskPlanSha256, authorityBundleSha256: ref.sha256 }, at }); assert.equal(reserved.decision._tag, 'Accepted');
            if (action === 'implement') {
                const changed = yield* ledger.executeChild({ ...common, childId: child.childId, operation: { _tag: 'RecordProductChange', reservationId, originReservationId: reservationId, baseCandidate, candidate: identity, allowedPathsSha256: child.allowedPathsSha256 }, at }); assert.equal(changed.decision._tag, 'Accepted');
            } else {
                const outcome = { schema: 'foreman.release-action-outcome.v1' as const, program: 'v040' as const, ...common, childId: child.childId, packageId: child.packageId, reservationAction: action, effectiveAction: action, reservationId, originReservationId: reservationId, candidateSha256: identity.candidateSha256, status: 'PASS' as const, evidenceSha256: reportRef.sha256, issuedAt: at }, outcomeSha256 = sha256Hex(bytes(outcome));
                yield* ledger.registerChildOutcome({ ...common, childId: child.childId, reservationId, originReservationId: reservationId, reservationAction: action, effectiveAction: action, candidateSha256: identity.candidateSha256, outcomeSha256, outcomeSchema: outcome.schema, registeredAt: at });
                const recorded = yield* ledger.executeChild({ ...common, childId: child.childId, operation: { _tag: 'RecordMilestone', milestone: 'checks', outcomeSha256, reservationId, originReservationId: reservationId, candidateSha256: identity.candidateSha256 }, at }); assert.equal(recorded.decision._tag, 'Accepted');
            }
        }
        const retained = new Map<string, typeof reportRef>();
        const register = (prior: Extract<PelReservationTokenV1, { kind: 'v2-child' }> | null, mismatch?: 'wrong-prior' | 'wrong-origin') => Effect.gen(function* () {
            const bundle: ReleaseEvidenceBundleV1 = { schema: 'foreman.release-evidence-bundle.v1', program: 'v040', ...common, childId: child.childId, packageId: child.packageId, action: prior ? 'provider_retry' : 'audit', candidate: identity, taskPlanSha256, receipts: [{ schema: 'foreman.design-approval.v1', program: 'v040', packageId: child.packageId, designCommit: identity.commit, designTree: identity.tree, approvedOpenSpecSha256: reportRef.sha256, taskPlanSha256, approvalStatementSha256: reportRef.sha256, issuedAt: at }, { schema: 'foreman.checks-evidence.v1', program: 'v040', packageId: child.packageId, candidate: identity, status: 'PASS', checksSha256: reportRef.sha256, issuedAt: at }], ...(prior ? { priorReservation: { reservationId: mismatch === 'wrong-prior' ? 'another-prior' : prior.reservationId, originReservationId: mismatch === 'wrong-origin' ? 'another-origin' : prior.operation.originReservationId, originalAction: 'audit' as const, candidate: identity, failureEvidenceSha256: reportRef.sha256 } } : {}), issuedAt: at };
            assert.equal(decodeReleaseAuthorityFileV1(bytes(bundle))._tag, 'Valid');
            const ref = yield* runtime.artifacts.put(fixture.context.binding.runId, bytes(bundle), 65536, 'ordinary'); retained.set(ref.sha256, ref);
            yield* ledger.registerChildAuthority({ ...common, childId: child.childId, action: bundle.action, effectiveAction: 'audit', candidate: identity, priorReservationId: bundle.priorReservation?.reservationId ?? null, originReservationId: bundle.priorReservation?.originReservationId ?? null, taskPlanSha256, bundleSha256: ref.sha256, receiptSchemas: bundle.receipts.map(r => r.schema), receiptSha256s: bundle.receipts.map(r => sha256Hex(bytes(r))), evaluationManifestSha256: null, registeredAt: at }); return ref;
        });
        const originalBundle = yield* register(null), binding = { ...fixture.context.binding, authority: { kind: 'v2-child' as const, ...common, childId: child.childId, authoritySha256: fixture.context.binding.authoritySha256, authorityRef: fixture.context.binding.authority.authorityRef, taskPlanSha256, authorityBundleSha256: originalBundle.sha256, originReservationId: 'original-implementation-origin' } };
        let context: HostContextV1 = { ...fixture.context, binding }, starts = 0; let lastIdentity: import('@foreman/providers').ProviderIdentityV1 | undefined;
        const candidate: CandidateRefV1 = { schemaVersion: 1, repository: binding.repository, workspaceGrantId: context.workspace.grantId, baseCommit: identity.commit, ...identity, treeDigest: 'd'.repeat(64), diffDigest: reportRef.sha256, allowedPathsSha256: child.allowedPathsSha256, artifactManifestSha256: reportRef.sha256, manifestRef: reportRef, diffRef: reportRef, producingAttempt: context.effect.attempt, producingEffectId: 'implementation' }, candidateRef = yield* put(candidate);
        const verification: VerificationReceiptV1 = { schemaVersion: 1, kind: 'verification', effect: context.effect, candidateRef, candidate: identity, gateId: 'candidate-full', gateDigest: pelHash(context.project.gates['candidate-full']), environmentDigest: pelHash({}), policyDigest: 'a'.repeat(64), passed: true, reportRef, observedAt: now, reservation: { schemaVersion: 1, kind: 'v1', effect: context.effect, preparationDigest: 'a'.repeat(64), operationDigest: 'b'.repeat(64), authoritySha256: binding.authoritySha256, reservationId: stablePelReservationId(context.effect.effectId, 'verify', 'a'.repeat(64)), candidate: identity, contractId: binding.contractId, contractSha256: binding.contractSha256, action: 'verify' } }, verificationRef = yield* put(verification);
        assert.ok(decodeCandidateRefV1(candidate).ok, JSON.stringify(decodeCandidateRefV1(candidate))); assert.ok(decodeVerificationReceiptV1(verification).ok, JSON.stringify(decodeVerificationReceiptV1(verification)));
        const services = makePelHostLibraryServices({ journal, ledger, processExec, runtime: () => runtime, transportVersion: () => Effect.succeed('v1'), retainAuthorityByHash: sha => Effect.sync(() => { const ref = retained.get(sha); assert.ok(ref); return ref; }) });
        const handler = makePelReviewHandler({ resolveInput: () => Effect.succeed({ candidate, candidateRef, verification, verificationRef, verificationValue: assoc({ status: str('verified'), passed: { tag: 'boolean', value: true }, candidate: str('artifact:' + candidateRef.artifactId), task: { tag: 'nil' }, verification: str('artifact:' + verificationRef.artifactId), checks: { tag: 'list', items: [] }, findings: { tag: 'list', items: [] } }), implementer: { kind: 'native', provider: 'xai', profileId: 'grok-4.6', transportId: 'grok-acp', credentialProfileRef: 'fixture', protocolVersion: 'v1', sessionId: 'implementation' }, artifacts: [] }), policy: () => Effect.succeed({ digest: 'a'.repeat(64), verificationPolicyDigest: 'a'.repeat(64), maxVerificationAgeMs: 10000, transportVersion: 'v1' }), actionAuthority: (_, ctx) => services.actionAuthority('audit', identity, ctx), recordReview: (receipt, ref, ctx) => receipt.verdict !== 'approved' ? Effect.void : recordPelReleaseMilestone(ledger, receipt, ref, 'audit', ctx, retained.get(receipt.reservation.kind === 'v2-child' ? receipt.reservation.operation.authorityBundleSha256 : '')!).pipe(Effect.provideService(PelRuntime, runtime), Effect.provideService(RunJournal, journal)) });
        const transport: ProviderTransport = { id: 'codex-app-server', version: 'v1', probe: () => Effect.die('unexpected probe'), resume: () => Effect.die('unexpected resume'), cancel: () => Effect.die('unexpected cancel'), observe: () => Effect.die('unexpected observe'), sendToolResult: () => Effect.die('unexpected tool'), start: request => Effect.sync(() => { starts++; const providerIdentity = { kind: 'native' as const, provider: 'openai', profileId: request.profileId, transportId: request.transportId, credentialProfileRef: request.credentialProfileRef, protocolVersion: 'v1', sessionId: `review-${starts}` }; lastIdentity = providerIdentity; return Stream.make({ schemaVersion: 1 as const, effectId: request.effectId, providerIdentity, payload: { type: 'usage' as const, usage: { inputTokens: 1, outputTokens: 1, costUsd: '0.001', providerCounters: {} } } }, { schemaVersion: 1 as const, effectId: request.effectId, providerIdentity, payload: { type: 'completed' as const, usage: { inputTokens: 1, outputTokens: 1, costUsd: '0.001', providerCounters: {} }, result: { value: assoc({ candidateSha256: str(identity.candidateSha256), verdict: str(starts < 3 ? 'unverified' : 'approved'), findings: { tag: 'list', items: [] } }), json: {}, schemaId: request.outputSchema.id, schemaSha256: pelHash(request.outputSchema.content), byteLength: 300 } } }); }) };
        Object.assign(runtime, { handlers: new Map([['fm/review', handler]]) }); Object.assign(runtime.providers, { resolve: () => Effect.succeed({ transport }) });
        yield* executeHostEffect(fixture.request, context).pipe(Effect.provideService(PelRuntime, runtime)); assert.equal(starts, 1);
        const replay = replayPelRun(yield* readPelRecords(binding.runId)); assert.ok(replay.ok); let prior = replay.value.intents.get(context.effect.effectId)!.reservation; assert.ok(prior?.kind === 'v2-child'); const origin = prior.reservationId;
        for (let ordinal = 1; ordinal <= (variant === 'two-retries' ? 2 : 1); ordinal++) {
            if (variant !== 'missing-grant') yield* register(prior, variant === 'two-retries' ? undefined : variant);
            context = { ...context, effect: stablePelEffectIdentity(binding, fixture.request.requestId, ordinal, prior.effect.effectId), retryContext: { parentRequestId: 'retry-review', attemptIndex: ordinal + 1, logicalOperationKey: 'review' } };
            const result = yield* executeHostEffect(fixture.request, context).pipe(Effect.either, Effect.provideService(PelRuntime, runtime));
            if (variant !== 'two-retries') { assert.equal(result._tag, 'Left'); assert.equal(starts, 1); break; }
            assert.equal(result._tag, 'Right', JSON.stringify(result)); assert.equal(starts, ordinal + 1); if (ordinal === 2) { assert.ok(result.right.kind === 'settled', JSON.stringify(result)); assert.equal(result.right.receipt.outcome.tag, 'success', JSON.stringify(result)); const recovered = yield* completePelHostProvider(context, { value: assoc({ candidateSha256: str(identity.candidateSha256), verdict: str('approved'), findings: { tag: 'list', items: [] } }), identity: lastIdentity! }).pipe(Effect.provideService(PelRuntime, runtime), Effect.either); assert.equal(recovered._tag, 'Right', JSON.stringify(recovered)); assert.equal(starts, 3); }
            const next = replayPelRun(yield* readPelRecords(binding.runId)); assert.ok(next.ok); prior = next.value.intents.get(context.effect.effectId)!.reservation; assert.ok(prior?.kind === 'v2-child'); assert.equal(prior.operation.originReservationId, origin); assert.equal(prior.operation.reservationAction, 'provider_retry'); assert.equal(prior.operation.effectiveAction, 'audit');
        }
        const state = (yield* ledger.familyStatus(common)).family.children[child.childId]!; assert.equal(state.counts.audit, 1); assert.equal(state.counts.provider_retry, variant === 'two-retries' ? 2 : 0); assert.equal(Boolean(state.milestones.audit), variant === 'two-retries');
    })).pipe(Effect.provide(liveProcessExec))); } finally { f.close(); }
});


test('retained action authority rejects open or malformed retry bindings', () => {
    const base = { taskPlanSha256: 'a'.repeat(64), authorityBundleSha256: 'b'.repeat(64) }, retry = { priorReservationId: 'prior', originReservationId: 'origin' };
    assert.ok(decodePelActionAuthorityV1(base).ok); assert.ok(decodePelActionAuthorityV1({ ...base, retry }).ok);
    for (const value of [{ ...base, retry: null }, { ...base, retry: {} }, { ...base, retry: { ...retry, extra: true } }, { ...base, retry: { ...retry, priorReservationId: '../escape' } }, { ...base, retry, extra: true }]) assert.equal(decodePelActionAuthorityV1(value).ok, false);
});
