/** Unshipped finite delivery fixture. All mutations stay inside its explicitly bound temporary root. */
import {mkdir,realpath,stat,lstat,writeFile,open} from 'node:fs/promises';
import {join,relative,isAbsolute} from 'node:path';
import {tmpdir} from 'node:os';
import {Effect,Layer,Stream} from 'effect';
import {canonicalize,sha256Hex} from '@foreman/core';
import {RunJournal,makeLiveRunJournalLayer} from '@foreman/event-log';
import {createAuthoringSnapshotV1,validateAuthoringSnapshotV1,resolveModelSelection,type AuthoringSnapshotV1,type PelDataValue,type JsonValue} from '@foreman/pel';
import {resolveProfile,type ProviderRequestV1,type ProviderTransport,type ProviderIdentityV1} from '@foreman/providers';
import {authoringFailure} from './pel-authoring-contract.js';
import {strictEndstopLimits,executionContractSha256,decodeExecutionContractV1,isExecutionContractFailure,type ExecutionContractV1} from './execution-contract.js';
import {EndstopLedger,makeLiveEndstopLedgerLayer} from './execution-ledger.js';
import {makeLiveRunLease} from './supervisor-live-services.js';
import {makeLivePelArtifactPort,pelHash,pelFailure,readPelRecords,replayPelRun} from './pel-journal.js';
import {makePelResourceScope} from './pel-resource-scope.js';
import {makePelControlHandlers} from './pel-control-functions.js';
import {makePelLifecycleServices,type PelLifecycleBackend} from './pel-lifecycle-services.js';
import {decodeForemanProjectV1} from './pel-project-config.js';
import {pelV1AllowedPathsSha256} from './pel-project-authority.js';
import {PelRuntime,type PelRuntimePorts,type ForemanProjectV1,type HostContextV1} from './pel-run-contract.js';
import {ProcessExec,liveProcessExec} from './queue-services.js';
import {makePelHostLibraryServices} from './pel-host-library.js';
import {makePelTaskHandler} from './pel-host-task.js';
import {projectPelHostReceiptEvidence,readPelHostEvidenceRecords,loadPelHostEvidence} from './pel-host-evidence.js';
import {readPelArtifactJson} from './pel-recovery.js';
import {decodeCandidateRefV1} from './pel-host-contract.js';
/** Exact asset schema. Relative paths resolve only beneath the manifest's canonical temporary root. */
export const pelDeliveryFixtureSettingsV1={schemaVersion:1,kind:'foreman.pel-delivery-fixture-settings.v1',evidenceKind:'test-fixture',projectId:'00000000-0000-4000-8000-000000000005',runtimeHandlerVersion:'1',paths:{workspace:'workspace',state:'state',publication:'remote.git'},writablePaths:['src'],requiredMilestones:['checks','audit'],taskActions:{implement:'implement',correct:'correct'},gate:{id:'candidate-full',argv:['/usr/bin/git','-c','core.fsmonitor=false','diff','--no-ext-diff','--no-textconv','--check'],environmentRefs:[],maxOutputBytes:4096,timeoutMs:5000},destination:{id:'reviewed-branch',operation:'publish',ref:'refs/heads/reviewed',expectedOldObject:{kind:'absent'},authority:'fixture:missing-publication'},roleSets:{'grok-sol':{implementer:{profileId:'grok-4.6',transportId:'grok-acp',credentialProfileRef:'account:test'},reviewer:{profileId:'gpt-5.6-sol',transportId:'codex-app-server',credentialProfileRef:'account:test'}},'astra-opus':{implementer:{profileId:'gpt-6-astra',transportId:'codex-app-server',credentialProfileRef:'account:test'},reviewer:{profileId:'claude-opus-5',transportId:'claude-code',credentialProfileRef:'account:test'}}},resultContract:{schemaId:'schema:delivery-final-v1',classification:'delivery-v1'}} as const;
export interface PelDeliveryFixtureV1 {readonly schemaVersion:1;readonly evidenceKind:'test-fixture';readonly fixtureId:string;readonly temporaryRoot:string;readonly stateRoot:string;readonly now:number;readonly scenario:'approved'|'gate-failed'|'repair-one'|'repair-noop'|'repair-exhausted';readonly roles:'grok-sol'|'astra-opus';readonly failurePoint:'none'|'after-provider-completed';}
const bad=()=>authoringFailure('PEL_SCHEMA','Invalid bounded delivery fixture manifest.');
const inside=(root:string,path:string)=>{const part=relative(root,path);return part!==''&&!part.startsWith('..')&&!isAbsolute(part);};
const object=(value:unknown):value is Record<string,unknown>=>value!==null&&typeof value==='object'&&!Array.isArray(value);
const io=<A>(f:()=>Promise<A>)=>Effect.tryPromise({try:f,catch:bad});
export function decodePelDeliveryFixture(value:unknown,assetRoot:string){return Effect.gen(function*(){
 if(!object(value)||Object.keys(value).sort().join(',')!=='evidenceKind,failurePoint,fixtureId,now,roles,scenario,schemaVersion,stateRoot,temporaryRoot'||value.schemaVersion!==1||value.evidenceKind!=='test-fixture'||typeof value.fixtureId!=='string'||!/^[-a-z0-9]{1,80}$/.test(value.fixtureId)||typeof value.temporaryRoot!=='string'||typeof value.stateRoot!=='string'||!Number.isSafeInteger(value.now)||Number(value.now)<=0||!['approved','gate-failed','repair-one','repair-noop','repair-exhausted'].includes(String(value.scenario))||!['grok-sol','astra-opus'].includes(String(value.roles))||!['none','after-provider-completed'].includes(String(value.failurePoint)))return yield* Effect.fail(bad());
 const fixture=value as unknown as PelDeliveryFixtureV1;
 yield* io(async()=>{if(!isAbsolute(fixture.temporaryRoot)||!isAbsolute(fixture.stateRoot)||await realpath(fixture.temporaryRoot)!==fixture.temporaryRoot||await realpath(fixture.stateRoot)!==fixture.stateRoot||!inside(await realpath(tmpdir()),fixture.temporaryRoot)||!inside(fixture.temporaryRoot,fixture.stateRoot)||!inside(fixture.temporaryRoot,await realpath(assetRoot))||!(await stat(fixture.stateRoot)).isDirectory())throw bad();});
 return fixture;
});}
const text=(value:string):PelDataValue=>({tag:'string',value});
const list=(items:PelDataValue[]=[]):PelDataValue=>({tag:'list',items});
const assoc=(fields:Record<string,PelDataValue>):PelDataValue=>list(Object.entries(fields).map(([key,value])=>({tag:'pair',key,value})));
/** Only fixed provider reports, file edits and Git argv are available to this executable. */
export function makePelDeliveryFixtureServices(fixture:PelDeliveryFixtureV1,base:AuthoringSnapshotV1,manifestHash:string,manifestBytes:Uint8Array,settingsBytes:Uint8Array){return Effect.gen(function*(){
 const decoded=yield* Effect.try({try:()=>JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(settingsBytes)) as unknown,catch:bad});if(canonicalize(decoded)!==canonicalize(pelDeliveryFixtureSettingsV1))return yield* Effect.fail(bad());
 const settings=decoded as typeof pelDeliveryFixtureSettingsV1;
 const root=fixture.stateRoot,workspace=join(fixture.temporaryRoot,settings.paths.workspace),remote=join(fixture.temporaryRoot,settings.paths.publication);if(root!==join(fixture.temporaryRoot,settings.paths.state))return yield* Effect.fail(bad());
 const proc=yield* Effect.flatMap(ProcessExec,Effect.succeed).pipe(Effect.provide(liveProcessExec));
 const git=(args:readonly string[],cwd=workspace)=>proc.runCaptured({command:'/usr/bin/git',args:['--no-replace-objects','-c','core.hooksPath=/dev/null','-c','core.fsmonitor=false',...args],cwd,env:{PATH:'/usr/bin:/bin',HOME:root,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'},maxOutputBytes:65536,timeoutMs:10000}).pipe(Effect.flatMap(r=>r.exitCode===0?Effect.succeed(r.stdout.trim()):Effect.fail(bad())),Effect.mapError(bad));
 const fresh=yield* io(async()=>{try{await lstat(workspace);return false;}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;await mkdir(workspace);return true;}});
 if(fresh){yield* git(['init','-q']);yield* git(['config','user.email','fixture@invalid']);yield* git(['config','user.name','Foreman fixture']);yield* io(async()=>{await mkdir(join(workspace,'src'));await writeFile(join(workspace,'src/main.ts'),'export const n = 1;\n',{flag:'wx'});});yield* git(['add','--','src/main.ts']);yield* git(['commit','-qm','Fixed fixture base']);yield* git(['init','--bare','-q',remote],fixture.temporaryRoot);}
 yield* io(async()=>{if(await realpath(workspace)!==workspace||await realpath(remote)!==remote)throw bad();});
 const common=join(workspace,'.git'),head=yield* git(['rev-parse','HEAD']),tree=yield* git(['rev-parse','HEAD^{tree}']),info=yield* io(()=>stat(workspace)),commonInfo=yield* io(()=>stat(common));
 const repository={gitCommonDir:common,identitySha256:pelHash({gitCommonDir:common,directoryIdentity:`${commonInfo.dev}:${commonInfo.ino}`})};
 const grant={grantId:'delivery-workspace',worktreeId:'delivery-worktree',canonicalRoot:workspace,directoryIdentity:`${info.dev}:${info.ino}`,immutableBase:head,writablePaths:settings.writablePaths,repository};
 const binding=(profileId:string,transportId:string)=>{const profile=base.providerProfiles.find(p=>p.profileId===profileId&&p.transportId===transportId);if(!profile)throw bad();return {profileId,transportId,credentialProfileRef:'account:test',controls:profile.applicationDefaults};};
 const roleSet=settings.roleSets[fixture.roles],roles={'role:implementer':binding(roleSet.implementer.profileId,roleSet.implementer.transportId),'role:reviewer':binding(roleSet.reviewer.profileId,roleSet.reviewer.transportId)};
 const snapshot=createAuthoringSnapshotV1({...base,roleBindings:roles,nlConditionProfile:null});if(!snapshot.ok)return yield* Effect.fail(bad());
 const execution={...strictEndstopLimits,implementationRounds:2,correctionRounds:2,auditRounds:4,totalActions:20},authorityRef={artifactId:`sha256-${manifestHash}`,byteLength:manifestBytes.byteLength,sha256:manifestHash};
 const contract:ExecutionContractV1={schemaVersion:1,contractId:'delivery-fixture-contract',packageId:'delivery-fixture',objectiveSha256:manifestHash,acceptanceSha256:manifestHash,baseCommit:head,allowedPathsSha256:pelV1AllowedPathsSha256([grant]),dependencyContractIds:[],authorizationSha256:manifestHash,createdAt:new Date(fixture.now).toISOString().replace(/\.\d{3}Z$/,'Z'),deadlineAt:new Date(fixture.now+execution.wallTimeMs).toISOString().replace(/\.\d{3}Z$/,'Z'),limits:execution,requiredMilestones:['checks','audit']};
 const retained=[contract,snapshot.value].map(value=>{const bytes=Buffer.from(canonicalize(value)),sha256=sha256Hex(bytes);return {ref:{artifactId:`sha256-${sha256}`,byteLength:bytes.byteLength,sha256},bytes};});retained.push({ref:authorityRef,bytes:Buffer.from(manifestBytes)});
 const project:ForemanProjectV1={schemaVersion:1,projectId:settings.projectId,repository,stateRoot:root,authorityRefs:[{kind:'v1',authoritySha256:manifestHash,authorityRef}],executionContractTemplate:retained[0]!.ref,authoringSnapshot:retained[1]!.ref,runtimeHandlerVersion:'1',limits:{execution,pel:snapshot.value.limits,maxConcurrentEffects:1,maxInputTokens:10000,maxOutputTokens:10000,maxToolCalls:0,maxOutputBytes:1048576,maxCostUsd:10,cancellationObservationMs:100,maxReplayReductions:100000},requiredMilestones:['checks','audit'],workspaces:{poolRoot:fixture.temporaryRoot,immutableBase:head,maxWorktrees:1,maxRaceContenders:1,grants:[grant]},gates:{[settings.gate.id]:{argv:settings.gate.argv,environmentRefs:settings.gate.environmentRefs,environmentSha256:pelHash({}),maxOutputBytes:settings.gate.maxOutputBytes,timeoutMs:settings.gate.timeoutMs}},destinations:{'reviewed-branch':{operation:'publish',repositoryIdentitySha256:repository.identitySha256,remoteIdentity:remote,ref:'refs/heads/reviewed',expectedOldObject:{kind:'absent'},authorityRef}},roleBindings:roles,taskActions:settings.taskActions,nlConditionProfile:null,dependencyMode:'ordered',resultContract:{schemaId:'schema:delivery-final-v1',schemaSha256:pelHash(snapshot.value.registry.dataSchemas['schema:delivery-final-v1']),classification:'delivery-v1'}};
 if(!decodeForemanProjectV1(project).ok)return yield* Effect.fail(bad());
 yield* io(()=>writeFile(join(root,'project-settings.json'),`${canonicalize(project)}\n`,{mode:0o600}));
 const runtime=yield* Effect.gen(function*(){
  const journal=yield* RunJournal,ledger=yield* EndstopLedger;yield* ledger.create(contract);const original=makeLivePelArtifactPort(root),resources=yield* makePelResourceScope();
  const artifacts:PelRuntimePorts['artifacts']={...original,put:(runId,bytes,max,protection)=>Effect.gen(function*(){
   if(fixture.failurePoint==='after-provider-completed'){
    const replay=replayPelRun(yield* readPelRecords(runId));if(!replay.ok)return yield* Effect.fail(replay.error);
    for(const row of replay.value.records){if(row.type!=='pel.effect.observed.v1'||row.data.externalOutcome!=='confirmed-complete'||!row.data.providerIdentity)continue;const value=yield* readPelArtifactJson(runId,row.data.observationRef).pipe(Effect.provideService(PelRuntime,{artifacts:original} as PelRuntimePorts));if(!object(value)||value.type!=='completed'||!object(value.result)||value.result.schemaId!=='schema:candidate-v1')continue;
     const first=yield* Effect.tryPromise({try:async()=>{try{const fd=await open(join(root,'provider-completed-kill'),'wx',0o600);try{await fd.writeFile(runId);await fd.sync();}finally{await fd.close();}return true;}catch(e){if((e as NodeJS.ErrnoException).code==='EEXIST')return false;throw e;}},catch:()=>pelFailure('journal-write-failed','The fixture death marker could not be retained.')});if(first){process.kill(process.pid,'SIGKILL');return yield* Effect.die('SIGKILL did not terminate the fixture owner.');}break;
    }
   }
   return yield* original.put(runId,bytes,max,protection);
  }).pipe(Effect.provideService(RunJournal,journal))};
  const runtime:PelRuntimePorts={artifacts,resources,handlers:new Map(),controls:new Map(makePelControlHandlers()),clock:{now:Effect.succeed(fixture.now),sleep:Effect.sleep},output:()=>Effect.void,validateDecisionAuthority:()=>Effect.fail(pelFailure('binding-mismatch','This fixture cannot grant operator authority.')),providers:{resolve:()=>Effect.fail(pelFailure('binding-mismatch','No finite provider cell.')),observe:identity=>Effect.succeed({status:'unsupported',providerIdentity:identity,reason:'Recorded provider completion is already in the owner journal.'}),permissions:{authorize:()=>Effect.fail({_tag:'UnsupportedCapability',retryClass:'never',message:'Fixture tools are forbidden.'}),submit:()=>Effect.fail({_tag:'UnsupportedCapability',retryClass:'never',message:'Fixture tools are forbidden.'})}},hostEvidence:binding=>Effect.gen(function*(){const state=yield* ledger.status(binding.contractId);const evidence=yield* projectPelHostReceiptEvidence(binding,state.currentCandidateSha256);return {...evidence,milestones:(['checks','audit','integrated','published'] as const).filter(name=>state.milestones[name]!==undefined)};}).pipe(Effect.provideService(PelRuntime,runtime),Effect.provideService(RunJournal,journal),Effect.mapError(()=>pelFailure('binding-mismatch','Fixture host evidence cannot be projected.'))),loadRunInputs:binding=>Effect.gen(function*(){
   if(binding.evidenceKind!=='test-fixture'||binding.stateRoot!==root||binding.authoritySha256!==manifestHash)return yield* Effect.fail(pelFailure('binding-mismatch','The run belongs to another fixture.'));
   const captured=decodeForemanProjectV1(yield* readPelArtifactJson(binding.runId,binding.artifacts.configuration)),stored=validateAuthoringSnapshotV1(yield* readPelArtifactJson(binding.runId,binding.artifacts.snapshot));if(!captured.ok||!stored.ok)return yield* Effect.fail(pelFailure('binding-mismatch','Captured delivery fixture settings changed.'));
   const saved=decodeExecutionContractV1(yield* readPelArtifactJson(binding.runId,captured.value.executionContractTemplate));if(isExecutionContractFailure(saved)||executionContractSha256(saved)!==binding.contractSha256)return yield* Effect.fail(pelFailure('binding-mismatch','Captured fixture authority changed.'));return {binding,project:captured.value,contract:saved,snapshot:stored.value,registry:stored.value.registry};
  }).pipe(Effect.provideService(PelRuntime,runtime))};
  const services=makePelHostLibraryServices({journal,ledger,processExec:proc,runtime:()=>runtime,transportVersion:()=>Effect.succeed('fixture-v1')});
  const task=makePelTaskHandler({resolveInput:services.resolveTaskInput,nativePolicy:()=>Effect.succeed({permissionGrantIds:['fixture-coding'],hostPermissionPortRef:'fixture-permission'}),transportVersion:()=>Effect.succeed('fixture-v1'),allowedPathsSha256:()=>Effect.succeed(contract.allowedPathsSha256),actionCandidate:(_action,context)=>Effect.gen(function*(){const evidence=yield* readPelHostEvidenceRecords(context);for(const entry of [...evidence.entries].reverse()){if(entry.kind!=='implementation')continue;const receipt=yield* loadPelHostEvidence(entry.ref,'implementation',context);if(receipt.kind==='implementation'&&receipt.candidateRef){const candidate=decodeCandidateRefV1(yield* readPelArtifactJson(context.binding.runId,receipt.candidateRef));if(!candidate.ok)return yield* Effect.fail(pelFailure('binding-mismatch','Fixture candidate evidence changed.'));return {commit:candidate.value.commit,tree:candidate.value.tree,candidateSha256:candidate.value.candidateSha256};}}return {commit:head,tree,candidateSha256:sha256Hex(head)};}).pipe(Effect.provideService(PelRuntime,runtime),Effect.provideService(RunJournal,journal)),actionAuthority:services.actionAuthority,recordImplementation:services.recordImplementation});
  const provider=(request:ProviderRequestV1,context:HostContextV1):ProviderTransport=>({id:request.transportId,version:'fixture-v1',probe:()=>Effect.die('Fixture has no metadata probe.'),resume:()=>Effect.die('Completed native task must never resume.'),cancel:()=>Effect.succeed({requested:true,acknowledged:false,localCleanup:'complete',remoteOutcome:'unknown'}),observe:identity=>Effect.succeed({status:'unsupported',providerIdentity:identity,reason:'No remote fixture.'}),sendToolResult:()=>Effect.die('Fixture exposes no tools.'),start:()=>Effect.gen(function*(){
   const implementing=request.outputSchema.id==='schema:candidate-v1',selection=roles[implementing?'role:implementer':'role:reviewer'];if(request.profileId!==selection.profileId||request.transportId!==selection.transportId||request.credentialProfileRef!==selection.credentialProfileRef||pelHash(request.controls)!==pelHash({...selection.controls,...(!implementing?{toolChoice:'none'}:{})}))return yield* Effect.fail({_tag:'UnsupportedCapability',retryClass:'never',message:'The exact finite fixture cell or controls changed.'} as const);
   const profile=resolveProfile(request.profileId);if(!profile.ok)return yield* Effect.fail(profile.error);const identity:ProviderIdentityV1={kind:'native',provider:profile.value.provider,profileId:request.profileId,transportId:request.transportId,credentialProfileRef:request.credentialProfileRef,protocolVersion:'fixture-v1',sessionId:context.effect.effectId};
   const state=yield* ledger.status(context.binding.contractId).pipe(Effect.mapError(()=>({_tag:'UnsupportedCapability',retryClass:'never',message:'Fixture ledger unavailable.'} as const)));const round=state.counts.implement+state.counts.correct;
   let value:PelDataValue,json:JsonValue;
   if(implementing){if(!(fixture.scenario==='repair-noop'&&round>1))yield* Effect.tryPromise({try:()=>writeFile(join(workspace,'src/main.ts'),`export const n = ${round+1};${fixture.scenario==='gate-failed'?' ':''}\n`),catch:()=>({_tag:'UnsupportedCapability',retryClass:'never',message:'Fixture edit failed.'} as const)});json={summary:'Recorded bounded implementation',claimedPaths:['invented-provider-claim.ts'],findings:[]};value=assoc({summary:text('Recorded bounded implementation'),claimedPaths:list([text('invented-provider-claim.ts')]),findings:list()});}
   else{const verify=request.artifacts.find(a=>a.id==='pel:verification')?.content;if(!object(verify)||!object(verify.candidate)||typeof verify.candidate.candidateSha256!=='string')return yield* Effect.fail({_tag:'OutputInvalid',retryClass:'never',message:'Fixture review lacks immutable candidate evidence.'} as const);const approved=fixture.scenario==='approved'||fixture.scenario==='repair-one'&&round>1;json={candidateSha256:verify.candidate.candidateSha256,verdict:approved?'approved':'changes-requested',findings:approved?[]:['Recorded correction is required.']};value=assoc({candidateSha256:text(verify.candidate.candidateSha256),verdict:text(approved?'approved':'changes-requested'),findings:approved?list():list([text('Recorded correction is required.')])});}
   return Stream.make({schemaVersion:1,effectId:request.effectId,providerIdentity:identity,payload:{type:'started'}} as const,{schemaVersion:1,effectId:request.effectId,providerIdentity:identity,payload:{type:'completed',result:{schemaId:request.outputSchema.id,value,json,schemaSha256:pelHash(request.outputSchema.content),byteLength:Buffer.byteLength(canonicalize(json))},usage:{inputTokens:10,outputTokens:5,costUsd:'0.01',providerCounters:{}}}} as const);
  })});
  Object.assign(runtime,{handlers:new Map([['fm/task',task],['fm/verify',services.verification],['fm/review',services.review],['fm/publish',services.publication]]),providers:{...runtime.providers,resolve:(request:ProviderRequestV1,context:HostContextV1)=>Effect.succeed({transport:provider(request,context)})}});
  return runtime;
 }).pipe(Effect.provide(Layer.mergeAll(makeLiveRunJournalLayer(root),makeLiveEndstopLedgerLayer(root))),Effect.mapError(()=>bad()));
 const loaded={project,baseSnapshot:snapshot.value,retainedInputs:retained,authority:{executionDeadline:Date.parse(contract.deadlineAt),binding:project.authorityRefs[0]!,contract,workspaceGrants:[grant],allowedTaskActions:project.taskActions,availableHandlers:new Set(['fm/task','fm/verify','fm/review','fm/publish','print','fm/checkpoint','fm/retry','fm/race'])}};
 const services=()=>Layer.mergeAll(Layer.succeed(PelRuntime,runtime),makeLiveRunJournalLayer(root),makeLiveEndstopLedgerLayer(root),makeLiveRunLease(root));const load=(override?:string)=>override&&override!==root?Effect.fail(bad()):Effect.succeed(loaded);
 const backend:PelLifecycleBackend={runtimeVersion:'1',evidenceKind:'test-fixture',now:Effect.succeed(fixture.now),load,configured:()=>Effect.succeed(loaded),configure:()=>Effect.fail(bad()),services,servicesForRun:(_runId,override)=>load(override).pipe(Effect.as(services())),preflight:checked=>Effect.gen(function*(){for(const effect of checked.analysis.effects){if(!loaded.authority.availableHandlers.has(effect.registryId))return yield* Effect.fail(bad());if(effect.registryId==='fm/task'||effect.registryId==='fm/review'){const expected=roles[effect.registryId==='fm/task'?'role:implementer':'role:reviewer'];if(effect.model&&(effect.model.profileId!==expected.profileId||effect.model.transportId!==expected.transportId))return yield* Effect.fail(bad());}}})};
 return makePelLifecycleServices(backend);
});}
