/** Execute the exact shipped control examples with the finite recorded delivery fixture. */
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {mkdtemp,mkdir,cp,readFile,writeFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {Effect} from 'effect';
import {sha256Hex} from '@foreman/core';
import {makeLiveRunJournalLayer,type RunId} from '@foreman/event-log';
import {EndstopLedger,makeLiveEndstopLedgerLayer} from './execution-ledger.js';
import {readPelRecords,replayPelRun} from './pel-journal.js';
const entry=resolve('packages/orchestration/dist-test/pel-cli-fixture.js');
async function fixture(name:'race-cancel'|'resume-checkpoint',crashRace=false){const root=await mkdtemp(join(tmpdir(),'pel-control-example-')),assetRoot=join(root,'assets'),stateRoot=join(root,'state');await mkdir(stateRoot);await cp(resolve('packages/orchestration/dist-test/assets'),assetRoot,{recursive:true});const manifest=join(root,'fixture.json');await writeFile(manifest,JSON.stringify({schemaVersion:1,assetRoot,assetManifestSha256:sha256Hex(await readFile(join(assetRoot,'manifest.json'))),fixtures:{responses:[],delivery:{schemaVersion:1,evidenceKind:'test-fixture',fixtureId:`m6-${name}`,temporaryRoot:root,stateRoot,now:Date.now(),scenario:'approved',roles:'grok-sol',failurePoint:crashRace?'after-race-decision':name==='resume-checkpoint'?'after-provider-completed':'none'}}}));const invoke=(...args:string[])=>spawnSync(process.execPath,[entry,'--fixture-manifest',manifest,...args,'--json'],{cwd:root,encoding:'utf8',timeout:60000});const records=(runId:string)=>Effect.runPromise(readPelRecords(runId as RunId).pipe(Effect.provide(makeLiveRunJournalLayer(stateRoot))));const ledger=()=>Effect.runPromise(Effect.flatMap(EndstopLedger,l=>l.status('delivery-fixture-contract')).pipe(Effect.provide(makeLiveEndstopLedgerLayer(stateRoot))));return {root,stateRoot,assetRoot,invoke,records,ledger,close:()=>rm(root,{recursive:true,force:true})};}
test('T-M6-023 exact race-cancel source selects an immutable candidate from separate real Git grants',async()=>{const f=await fixture('race-cancel');let passed=false;try{assert.deepEqual(await readFile(join(f.assetRoot,'examples/pel/race-cancel.pel')),await readFile('examples/pel/race-cancel.pel'));const run=f.invoke('run','examples/pel/race-cancel.pel');assert.equal(run.status,0,run.stdout+run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.state,'succeeded');assert.equal(result.evidenceKind,'test-fixture');assert.ok(result.checks,run.stdout);assert.ok(result.review,run.stdout);assert.equal(result.checks.passed,true);assert.equal(result.review.verdict,'approved');const settings=JSON.parse(await readFile(join(f.stateRoot,'project-settings.json'),'utf8'));assert.equal(settings.workspaces.grants.length,2);assert.notEqual(settings.workspaces.grants[0].canonicalRoot,settings.workspaces.grants[1].canonicalRoot);const replay=replayPelRun(await f.records(result.runId));assert.ok(replay.ok);assert.equal(replay.value.records.filter(row=>row.type==='pel.race.decision.v1').length,1);const children=new Map<string,{phase:string}>();for(const row of replay.value.records){if(row.type!=='pel.child-suspension.v1')continue;const child=JSON.parse(await readFile(join(f.stateRoot,'runs',result.runId,'artifacts',row.data.childRef.artifactId),'utf8'));children.set(child.childInvocationId,child);}assert.equal(children.size,2);assert.ok([...children.values()].every(child=>child.phase==='done'||child.phase==='abandoned'));assert.equal(result.usage.unresolvedEffectIds.length,0);assert.equal((await f.ledger()).counts.implement,2);const before=await f.ledger(),resumed=f.invoke('resume',result.runId);assert.ok([0,2].includes(resumed.status??-1),resumed.stdout+resumed.stderr);assert.deepEqual(await f.ledger(),before);const after=replayPelRun(await f.records(result.runId));assert.ok(after.ok);assert.equal(after.value.records.filter(row=>row.type==='pel.race.decision.v1').length,1);passed=true;}finally{if(passed)await f.close();else console.error(`Retained race diagnostic: ${f.root}`);}});
test('T-M6-023 exact resume-checkpoint source survives provider completion death without another implementation',async()=>{const f=await fixture('resume-checkpoint');try{assert.deepEqual(await readFile(join(f.assetRoot,'examples/pel/resume-checkpoint.pel')),await readFile('examples/pel/resume-checkpoint.pel'));const killed=f.invoke('run','examples/pel/resume-checkpoint.pel');assert.equal(killed.signal,'SIGKILL',killed.stdout+killed.stderr);const runId=(await readFile(join(f.stateRoot,'provider-completed-kill'),'utf8')).trim(),before=replayPelRun(await f.records(runId));assert.ok(before.ok);assert.equal(before.value.records.filter(row=>row.type==='pel.checkpoint.v1').length,1);const resumed=f.invoke('resume',runId);assert.equal(resumed.status,0,resumed.stdout+resumed.stderr);const result=JSON.parse(resumed.stdout);assert.equal(result.state,'succeeded');assert.equal(result.review.verdict,'approved');const after=replayPelRun(await f.records(runId));assert.ok(after.ok);assert.equal(after.value.records.filter(row=>row.type==='pel.checkpoint.v1').length,1);const state=await f.ledger();assert.equal(state.counts.implement,1);assert.equal(state.counts.verify,1);assert.equal(state.counts.audit,1);}finally{await f.close();}});

test('M6 race crash after winner decision settles the known completed loser without another task completion',async()=>{const f=await fixture('race-cancel',true);let passed=false;try{const killed=f.invoke('run','examples/pel/race-cancel.pel');assert.equal(killed.signal,'SIGKILL',killed.stdout+killed.stderr);const runId=(await readFile(join(f.stateRoot,'race-decision-kill'),'utf8')).trim(),before=replayPelRun(await f.records(runId));assert.ok(before.ok);assert.equal(before.value.records.filter(row=>row.type==='pel.race.decision.v1').length,1);const unresolved=[...before.value.intents.values()].filter(intent=>!before.value.results.has(intent.effect.effectId));assert.equal(unresolved.length,1);assert.equal(before.value.observations.get(unresolved[0]!.effect.effectId)?.externalOutcome,'confirmed-complete');const completedBefore=before.value.records.filter(row=>row.type==='pel.effect.observed.v1'&&row.data.externalOutcome==='confirmed-complete').length;const resumed=f.invoke('resume',runId);assert.equal(resumed.status,0,resumed.stdout+resumed.stderr);const result=JSON.parse(resumed.stdout);assert.equal(result.state,'succeeded');assert.equal(result.review.verdict,'approved');const after=replayPelRun(await f.records(runId));assert.ok(after.ok);assert.equal(after.value.records.filter(row=>row.type==='pel.race.decision.v1').length,1);const cancelled=after.value.results.get(unresolved[0]!.effect.effectId);assert.ok(cancelled);const receipt=JSON.parse(await readFile(join(f.stateRoot,'runs',runId,'artifacts',cancelled.receiptRef.artifactId),'utf8'));assert.equal(receipt.outcome.failure.code,'cancelled');assert.equal((await f.ledger()).counts.implement,2);assert.equal((await f.ledger()).counts.audit,1);assert.equal((await f.ledger()).counts.verify,1);assert.ok(after.value.records.filter(row=>row.type==='pel.effect.observed.v1'&&row.data.externalOutcome==='confirmed-complete').length>=completedBefore);passed=true;}finally{if(passed)await f.close();else console.error(`Retained race recovery diagnostic: ${f.root}`);}});
