/** Local integration fixture. No production entry imports this authority setup. */
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {writeFileSync,statSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {Effect} from 'effect';
import {canonicalize,sha256Hex} from '@foreman/core';
import {RunJournal,type RunId,type LaneId} from '@foreman/event-log';
import {decodeReleaseAuthorityFileV1,type ReleaseActionV1,type ReleaseEvidenceBundleV1,type ReleaseActionOutcomeV1,type ReleaseAuthorityReceiptV1} from '@foreman/policy';
import type {PelDataValue} from '@foreman/pel';
import {pelHostFixture} from './pel-host-test-fixture.js';
import {deriveExecutionContractFamilyV2,executionContractSha256,type ExecutionContractV1} from './execution-contract.js';
import {PelRuntime,type ExecutionBindingV1,type ForemanProjectV1,type PelAuthorityBindingV1,type PelReservationTokenV1,type PelRuntimePorts,type PelOwnedRunContextV1} from './pel-run-contract.js';
import {appendPelRecord,pelHash,pelFailure,stablePelEffectIdentity,stablePelReservationId,readPelRecords,replayPelRun} from './pel-journal.js';
import {makePelPublishHandler,makePelPublicationRecorder,type PelPublicationResolvedInputV1} from './pel-host-publish.js';
import {makePelPublicationService} from './pel-publication-service.js';
import {recordPelReleaseMilestone} from './pel-host-milestone.js';
import {makeLiveRunLease} from './supervisor-live-services.js';
import {runProgram,withPelRunOwner} from './pel-runner.js';
import {resumeProgram,readPelArtifactJson} from './pel-recovery.js';
import {inspectPelCandidate,capturePelCandidate,type PelCapturedCandidateV1} from './pel-candidate-capture.js';
import {decodeCandidateRefV1,decodeVerificationReceiptV1,decodeReviewReceiptV1,type CandidateRefV1} from './pel-host-contract.js';
import {ProcessExec,liveProcessExec} from './queue-services.js';
const rows=[['v040-t2-project-registry','project-registry',[]],['v040-t3-memory-index','external-memory-index',['v040-t2-project-registry']],['v040-t4-appliance','hermetic-foreman-appliance',[]],['v040-t5-graphify','knowledge-plane-refresh',[]],['v040-t6-work-dag','work-dag-projection',['v040-t5-graphify']],['v040-t7-context','graph-context-builder',['v040-t6-work-dag']],['v040-t8-evaluation','graph-eval-falsification',['v040-t3-memory-index','v040-t4-appliance','v040-t7-context']],['v040-t9-release','v040-release-program',['v040-t2-project-registry','v040-t3-memory-index','v040-t4-appliance','v040-t5-graphify','v040-t6-work-dag','v040-t7-context','v040-t8-evaluation']]] as const;
const source='(fm/publish :id "publish" :input "artifact:approved-spec" :destination "destination:pull-request")';
const bytes=(value:unknown)=>Buffer.from(canonicalize(value)+'\n');
const git=(cwd:string,...args:string[])=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
const str=(value:string):PelDataValue=>({tag:'string',value});
const assoc=(fields:Record<string,PelDataValue>):PelDataValue=>({tag:'list',items:Object.entries(fields).map(([key,value])=>({tag:'pair',key,value}))});
export function makePublicationIntegrationFixture(options:{deferredAuthority?:boolean;syntheticCapture?:boolean}={}){
 const f=pelHostFixture(source),workspace=join(f.root,'work'),remote=join(f.root,'remote.git');git(f.root,'init','--quiet',workspace);git(workspace,'config','user.name','Fixture');git(workspace,'config','user.email','fixture@example.invalid');writeFileSync(join(workspace,'file.ts'),'export const value = 1;\n');git(workspace,'add','.');git(workspace,'commit','--quiet','-m','base');const base=git(workspace,'rev-parse','HEAD'),baseTree=git(workspace,'rev-parse','HEAD^{tree}'),baseIndex=readFileSync(join(workspace,'.git/index'));git(f.root,'init','--quiet','--bare',remote);git(workspace,'push','--quiet',remote,`${base}:refs/heads/reviewed`);let commit='',tree='';const createCandidate=()=>{writeFileSync(join(workspace,'file.ts'),'export const value = 2;\n');git(workspace,'add','.');git(workspace,'commit','--quiet','-m','candidate');commit=git(workspace,'rev-parse','HEAD');tree=git(workspace,'rev-parse','HEAD^{tree}');};if(!options.deferredAuthority&&!options.syntheticCapture)createCandidate();
 let pushes=0,dropAck=false,denyObservation=false,mutation:null|'candidate'|'target'=null;
 const setup=Effect.gen(function*(){
  const original=yield* f.setup,ledger=original.ledger,journal=yield* RunJournal,process=yield* ProcessExec,runId='publication-real' as RunId,attempt=yield* journal.allocate(runId,'pel' as LaneId),now=original.now,at=new Date(now).toISOString().replace('.000Z','Z');
  const put=(value:unknown)=>original.runtime.artifacts.put(runId,Buffer.from(canonicalize(value)),64*1024*1024,'ordinary'),putCanonical=(value:unknown)=>original.runtime.artifacts.put(runId,bytes(value),64*1024*1024,'ordinary');
  const authorityRef=yield* putCanonical({scope:'Temporary local publication fixture',remote,ref:'refs/heads/reviewed',base,...(options.deferredAuthority?{authorityRef:null}:{commit})});
  const contract:ExecutionContractV1={...(yield* ledger.status(original.context.binding.contractId)).contract,contractId:'publication-contract',baseCommit:base,authorizationSha256:authorityRef.sha256,limits:{...original.context.binding.limits.execution,resumeAttempts:3},requiredMilestones:['checks','audit','integrated','published']};yield* ledger.create(contract);
  const stat=statSync(workspace),commonStat=statSync(join(workspace,'.git')),repository={gitCommonDir:join(workspace,'.git'),identitySha256:sha256Hex(canonicalize({gitCommonDir:join(workspace,'.git'),directoryIdentity:`${commonStat.dev}:${commonStat.ino}`}))},grant={...original.context.workspace,repository,canonicalRoot:workspace,directoryIdentity:`${stat.dev}:${stat.ino}`,immutableBase:base,writablePaths:['file.ts']};
  let captured:PelCapturedCandidateV1|null=null;
  if(options.syntheticCapture){
   assert.equal(git(workspace,'rev-parse','HEAD'),base);
   const captureBinding={...original.context.binding,runId,attempt,repository},captureContext={...original.context,binding:captureBinding,workspace:grant,project:{...original.context.project,repository},effect:stablePelEffectIdentity(captureBinding,'captured-fixture-candidate')};
   captured=yield* Effect.gen(function*(){const before=yield* inspectPelCandidate(captureContext);writeFileSync(join(workspace,'file.ts'),'export const value = 2;\n');return yield* capturePelCandidate(before,captureContext);}).pipe(Effect.provideService(PelRuntime,original.runtime),Effect.scoped);
   assert.ok(captured.commit&&captured.tree&&captured.treeDigest);commit=captured.commit;tree=captured.tree;
   assert.equal(git(workspace,'rev-parse','HEAD'),base);assert.ok(readFileSync(join(workspace,'.git/index')).equals(baseIndex));
  }else if(options.deferredAuthority){assert.equal(git(workspace,'rev-parse','HEAD'),base);createCandidate();}
  const rootContractSha256=executionContractSha256(contract),familySource={schema:'foreman.execution-family-source.v1',program:'v040',familyId:'v040-release-20260822-f1',children:rows.map(([childId,packageId,dependencyChildIds],index)=>({schema:'foreman.execution-child-brief.v1',childId,packageId,dependencyChildIds,tranche:index+2,objective:'Temporary local publication prerequisite',acceptance:['The local fixture records canonical checks'],allowedPaths:['file.ts']}))};
  const familySourceRef=yield* putCanonical(familySource),derived=deriveExecutionContractFamilyV2({rootContractId:contract.contractId,rootContractSha256,track1Commit:base,track1Tree:baseTree,sourceBytes:bytes(familySource),createdAt:at});assert.equal(derived._tag,'Valid');if(derived._tag!=='Valid')throw Error(JSON.stringify(derived));
  const common={rootContractId:contract.contractId,rootContractSha256,familySha256:derived.familySha256},familyApproval=yield* putCanonical({familySha256:derived.familySha256,sourceSha256:familySourceRef.sha256,purpose:'Local integration fixture authority'});
  yield* ledger.registerFamilyAuthority({...common,manifest:derived.manifest,sourceSha256:familySourceRef.sha256,auditReceiptSha256:familyApproval.sha256,userReceiptSha256:authorityRef.sha256,registeredAt:at});yield* ledger.activateFamily({...common,sourceSha256:familySourceRef.sha256,auditReceiptSha256:familyApproval.sha256,userReceiptSha256:authorityRef.sha256,activatedAt:at});
  const candidate={commit,tree,candidateSha256:sha256Hex(commit)},baseCandidate={commit:base,tree:baseTree,candidateSha256:sha256Hex(base)},taskPlan=yield* putCanonical({task:'Publish the verified temporary candidate',base,commit}),report=yield* putCanonical({checks:'Local deterministic host fixture passed',candidate});
  const bundleFor=(childId:string,packageId:string,action:ReleaseActionV1,identity:typeof candidate)=>Effect.gen(function*(){
   const design:ReleaseAuthorityReceiptV1={schema:'foreman.design-approval.v1',program:'v040',packageId,designCommit:base,designTree:baseTree,approvedOpenSpecSha256:familySourceRef.sha256,taskPlanSha256:taskPlan.sha256,approvalStatementSha256:authorityRef.sha256,issuedAt:at};
   const checks:ReleaseAuthorityReceiptV1={schema:'foreman.checks-evidence.v1',program:'v040',packageId,candidate:identity,status:'PASS',checksSha256:report.sha256,issuedAt:at};
   const audit:ReleaseAuthorityReceiptV1={schema:'foreman.release-audit.v1',program:'v040',packageId,candidate:identity,verdict:'APPROVED',findings:[],evidenceSha256:report.sha256,issuedAt:at};
   const bundle:ReleaseEvidenceBundleV1={schema:'foreman.release-evidence-bundle.v1',program:'v040',...common,childId,packageId,action,candidate:identity,taskPlanSha256:taskPlan.sha256,receipts:action==='audit'?[design,checks]:action==='integrate'||action==='publish'?[design,audit]:[design],issuedAt:at};
   assert.equal(decodeReleaseAuthorityFileV1(bytes(bundle))._tag,'Valid');const ref=yield* putCanonical(bundle);return {bundle,ref,registration:{...common,childId,action,effectiveAction:action,priorReservationId:null,originReservationId:null,candidate:identity,taskPlanSha256:taskPlan.sha256,bundleSha256:ref.sha256,receiptSchemas:bundle.receipts.map(value=>value.schema),receiptSha256s:bundle.receipts.map(value=>sha256Hex(bytes(value))),evaluationManifestSha256:null,registeredAt:at}};
  });
  const selected=derived.manifest.children.find(child=>child.tranche===9)!;
  let integrationReceiptRef=report,verifyToken:PelReservationTokenV1|null=null,auditToken:PelReservationTokenV1|null=null,verifyBundle=report,auditBundle=report;
  for(const child of derived.manifest.children){
   for(const action of ['implement','verify','audit','integrate'] as const){
    if(child.tranche===8&&action==='integrate'){
     const evaluationDesign=(yield* bundleFor(child.childId,child.packageId,'verify',candidate)).bundle.receipts[0]!,manifestRef=yield* putCanonical({fixture:true,plannedRuns:2000,execution:'not-run'}),evaluationReceipt={schema:'foreman.evaluation-authority.v1' as const,program:'v040' as const,packageId:'graph-eval-falsification' as const,manifestSha256:manifestRef.sha256,issuedAt:at},receiptRef=yield* putCanonical(evaluationReceipt),evaluationBundle:ReleaseEvidenceBundleV1={schema:'foreman.release-evidence-bundle.v1',program:'v040',...common,childId:child.childId,packageId:child.packageId,action:'evaluate',candidate,taskPlanSha256:taskPlan.sha256,receipts:[evaluationDesign,evaluationReceipt],issuedAt:at},bundleRef=yield* putCanonical(evaluationBundle);assert.equal(decodeReleaseAuthorityFileV1(bytes(evaluationBundle))._tag,'Valid');
     yield* ledger.registerChildAuthority({...common,childId:child.childId,action:'evaluate',effectiveAction:'evaluate',priorReservationId:null,originReservationId:null,candidate,taskPlanSha256:taskPlan.sha256,bundleSha256:bundleRef.sha256,receiptSchemas:[evaluationDesign.schema,evaluationReceipt.schema],receiptSha256s:[sha256Hex(bytes(evaluationDesign)),receiptRef.sha256],evaluationManifestSha256:manifestRef.sha256,registeredAt:at});
     const reservationId='fixture-evaluation';const reserved=yield* ledger.executeChild({...common,childId:child.childId,operation:{_tag:'ReserveAction',reservationId,reservationAction:'evaluate',effectiveAction:'evaluate',originReservationId:reservationId,candidate,taskPlanSha256:taskPlan.sha256,authorityBundleSha256:bundleRef.sha256},at});assert.equal(reserved.decision._tag,'Accepted');
     const runSet=yield* put([]),verdict={schema:'foreman.evaluation-verdict.v1',program:'v040',...common,childId:child.childId,packageId:child.packageId,candidateSha256:candidate.candidateSha256,authorityManifestSha256:manifestRef.sha256,evaluationAuthorityReceiptSha256:receiptRef.sha256,result:'GRAPH_OFF_UNCOMPUTABLE' as const,plannedRuns:2000,completedRuns:0,unavailableRuns:0,notRunRuns:2000,runSetSha256:runSet.sha256,reportSha256:report.sha256,issuedAt:at},verdictRef=yield* putCanonical(verdict);assert.equal(decodeReleaseAuthorityFileV1(bytes(verdict))._tag,'Valid');
     yield* ledger.registerEvaluationVerdict({...common,childId:child.childId,candidateSha256:candidate.candidateSha256,result:verdict.result,completedRuns:0,unavailableRuns:0,notRunRuns:2000,runSetSha256:runSet.sha256,evaluationAuthorityReceiptSha256:receiptRef.sha256,verdictSha256:verdictRef.sha256,registeredAt:at});
    }

    const identity=action==='implement'?baseCandidate:candidate,prepared=yield* bundleFor(child.childId,child.packageId,action,identity);yield* ledger.registerChildAuthority(prepared.registration);
    const effect=stablePelEffectIdentity({...original.context.binding,runId,attempt},`${child.childId}-${action}`),preparationDigest=prepared.ref.sha256,reservationId=stablePelReservationId(effect.effectId,action,preparationDigest),operation={_tag:'ReserveAction' as const,reservationId,reservationAction:action,effectiveAction:action,originReservationId:reservationId,candidate:identity,taskPlanSha256:taskPlan.sha256,authorityBundleSha256:prepared.ref.sha256};
    const reserved=yield* ledger.executeChild({...common,childId:child.childId,operation,at});assert.equal(reserved.decision._tag,'Accepted',JSON.stringify(reserved.decision));
    if(action==='implement'){const changed=yield* ledger.executeChild({...common,childId:child.childId,operation:{_tag:'RecordProductChange',reservationId,originReservationId:reservationId,baseCandidate,candidate,allowedPathsSha256:child.allowedPathsSha256},at});assert.equal(changed.decision._tag,'Accepted');continue;}
    if(child.childId===selected.childId&&(action==='verify'||action==='audit')){const token:PelReservationTokenV1={schemaVersion:1,kind:'v2-child',effect,preparationDigest,operationDigest:pelHash(operation),authoritySha256:authorityRef.sha256,reservationId,candidate,...common,childId:child.childId,operation};if(action==='verify'){verifyToken=token;verifyBundle=prepared.ref;}else{auditToken=token;auditBundle=prepared.ref;}}
    const outcome:ReleaseActionOutcomeV1={schema:'foreman.release-action-outcome.v1',program:'v040',...common,childId:child.childId,packageId:child.packageId,reservationAction:action,effectiveAction:action,reservationId,originReservationId:reservationId,candidateSha256:candidate.candidateSha256,status:'PASS',evidenceSha256:report.sha256,issuedAt:at};assert.equal(decodeReleaseAuthorityFileV1(bytes(outcome))._tag,'Valid');const outcomeRef=yield* putCanonical(outcome);
    if(child.childId===selected.childId&&action==='integrate')integrationReceiptRef=outcomeRef;
    yield* ledger.registerChildOutcome({...common,childId:child.childId,reservationId,originReservationId:reservationId,reservationAction:action,effectiveAction:action,candidateSha256:candidate.candidateSha256,outcomeSha256:outcomeRef.sha256,outcomeSchema:'foreman.release-action-outcome.v1',registeredAt:at});const recorded=yield* ledger.executeChild({...common,childId:child.childId,operation:{_tag:'RecordMilestone',milestone:action==='verify'?'checks':action==='audit'?'audit':'integrated',outcomeSha256:outcomeRef.sha256,reservationId,originReservationId:reservationId,candidateSha256:candidate.candidateSha256},at});assert.ok(['Accepted','Terminated'].includes(recorded.decision._tag),JSON.stringify({child:child.childId,action,decision:recorded.decision}));
   }
  }
  assert.ok(verifyToken&&auditToken);const publication=yield* bundleFor(selected.childId,selected.packageId,'publish',candidate),authority:Extract<PelAuthorityBindingV1,{kind:'v2-child'}>={kind:'v2-child',...common,childId:selected.childId,authoritySha256:authorityRef.sha256,authorityRef,originReservationId:verifyToken.reservationId,taskPlanSha256:taskPlan.sha256,authorityBundleSha256:verifyBundle.sha256};
  const snapshot=original.context.checked.snapshot,sourceRef=yield* original.runtime.artifacts.put(runId,Buffer.from(source),65536,'ordinary'),snapshotRef=yield* put(snapshot),registryRef=yield* put(snapshot.registry),project:ForemanProjectV1={...original.context.project,repository,limits:{...original.context.project.limits,execution:contract.limits},authorityRefs:[authority],executionContractTemplate:yield* put(contract),workspaces:{...original.context.project.workspaces,grants:[grant],immutableBase:base},destinations:{'destination:pull-request':{operation:'publish',repositoryIdentitySha256:repository.identitySha256,remoteIdentity:remote,ref:'refs/heads/reviewed',expectedOldObject:{kind:'exact',oid:base},authorityRef:options.deferredAuthority?null:publication.ref}},requiredMilestones:contract.requiredMilestones};
  const configuration=yield* put(project),binding:ExecutionBindingV1={...original.context.binding,limits:{...original.context.binding.limits,execution:contract.limits},runId,attempt,contractId:contract.contractId,contractSha256:rootContractSha256,authority,authoritySha256:authorityRef.sha256,configurationDigest:configuration.sha256,repository,artifacts:{source:sourceRef,snapshot:snapshotRef,registry:registryRef,configuration},requiredMilestones:contract.requiredMilestones};
  const candidateValue:CandidateRefV1={schemaVersion:1,repository,workspaceGrantId:grant.grantId,baseCommit:base,...candidate,treeDigest:captured?.treeDigest??sha256Hex(tree),diffDigest:captured?.diffRef.sha256??report.sha256,allowedPathsSha256:selected.allowedPathsSha256,artifactManifestSha256:captured?.artifactManifestSha256??report.sha256,manifestRef:captured?.manifestRef??report,diffRef:captured?.diffRef??report,producingAttempt:captured?.attempt??attempt,producingEffectId:captured?.effectId??'captured-fixture-candidate'},candidateRef=yield* put(candidateValue);
  const verification={schemaVersion:1 as const,kind:'verification' as const,effect:verifyToken.effect,candidateRef,candidate,gateId:'candidate-full',gateDigest:pelHash(project.gates['candidate-full']),environmentDigest:project.gates['candidate-full']!.environmentSha256,policyDigest:verifyBundle.sha256,passed:true,reportRef:report,reservation:verifyToken,observedAt:now},verificationRef=yield* put(verification);
  const provider=(name:string)=>({kind:'api' as const,provider:name,profileId:name==='xai'?'grok-4.6':'gpt-5.6-sol',transportId:name==='xai'?'xai-responses':'openai-responses',credentialProfileRef:'fixture:account',endpointRevision:'fixture',responseId:'fixture'});
  const review={schemaVersion:1 as const,kind:'review' as const,effect:auditToken.effect,candidateRef,candidate,verificationRef,implementer:provider('xai'),reviewer:provider('openai'),policyId:'independent-review',policyDigest:auditBundle.sha256,verdict:'approved' as const,findings:[],reportRef:report,reservation:auditToken,observedAt:now},reviewRef=yield* put(review);
  const checkedValue=assoc({status:str('verified'),passed:{tag:'boolean',value:true},candidate:str('artifact:'+candidateRef.artifactId),task:{tag:'nil'},verification:str('artifact:'+verificationRef.artifactId),checks:{tag:'list',items:[]},findings:{tag:'list',items:[]}}),delivery=assoc({status:str('approved'),approved:{tag:'boolean',value:true},candidate:str('artifact:'+candidateRef.artifactId),verification:checkedValue,review:str('artifact:'+reviewRef.artifactId),verdict:str('approved'),findings:{tag:'list',items:[]}}),resolved:PelPublicationResolvedInputV1={candidate:candidateValue,candidateRef,verification,verificationRef,review,reviewRef,delivery,integrationReceiptRef};
  const inputs:Omit<PelOwnedRunContextV1,'owner'>={binding,project,contract,snapshot,registry:snapshot.registry};
  const processExec:ProcessExec['Type']={...process,runCaptured:options=>Effect.gen(function*(){if(options.args.includes('push')){pushes++;const result=yield* process.runCaptured(options);if(dropAck)return yield* Effect.fail({_tag:'ProcessFailure' as const,reason:'timeout' as const});return result;}if(denyObservation&&options.args.includes('ls-remote'))return yield* Effect.fail({_tag:'ProcessFailure' as const,reason:'timeout' as const});const result=yield* process.runCaptured(options);if(mutation&&options.args.includes('ls-remote')){if(mutation==='candidate')writeFileSync(join(workspace,'file.ts'),'changed after prepare\n');else git(f.root,'--git-dir',remote,'update-ref','-d','refs/heads/reviewed');mutation=null;}return result;})};
  const service=makePelPublicationService({ledger,processExec,...(options.syntheticCapture?{resolveCapturedCandidate:(input:import('./pel-publication-service.js').PelPublicationInputV1,context:import('./pel-run-contract.js').HostContextV1)=>Effect.gen(function*(){assert.deepEqual(input.evidenceRefs[0],candidateRef);const stored=decodeCandidateRefV1(yield* readPelArtifactJson(context.binding.runId,candidateRef));assert.ok(stored.ok);assert.deepEqual(stored.value,candidateValue);return stored.value;})}:{}),readAuthority:ref=>original.runtime.artifacts.get(runId,ref,65536),readAuthorityHash:sha=>{assert.equal(sha,publication.ref.sha256);return Effect.map(original.runtime.artifacts.get(runId,publication.ref,65536),bytes=>({ref:publication.ref,bytes}));},validateEvidence:(input,context)=>Effect.gen(function*(){
   assert.deepEqual(input.evidenceRefs,[candidateRef,verificationRef,reviewRef]);assert.deepEqual(input.integrationReceiptRef,integrationReceiptRef);
   const integration=decodeReleaseAuthorityFileV1(yield* original.runtime.artifacts.get(runId,integrationReceiptRef,65536));assert.equal(integration._tag,'Valid');if(integration._tag!=='Valid'||integration.value.schema!=='foreman.release-action-outcome.v1')throw Error('Invalid integration receipt');assert.equal(integration.value.candidateSha256,candidate.candidateSha256);assert.equal(integration.value.childId,selected.childId);assert.equal(integration.value.status,'PASS');
   const actualCandidate=decodeCandidateRefV1(yield* readPelArtifactJson(context.binding.runId,candidateRef)),actualVerification=decodeVerificationReceiptV1(yield* readPelArtifactJson(context.binding.runId,verificationRef)),actualReview=decodeReviewReceiptV1(yield* readPelArtifactJson(context.binding.runId,reviewRef));
   assert.ok(actualCandidate.ok&&actualVerification.ok&&actualReview.ok);assert.deepEqual(actualCandidate.value,candidateValue);assert.deepEqual(actualVerification.value,verification);assert.deepEqual(actualReview.value,review);
   assert.deepEqual(actualVerification.value.candidateRef,candidateRef);assert.deepEqual(actualReview.value.verificationRef,verificationRef);assert.notEqual(actualReview.value.implementer.provider,actualReview.value.reviewer.provider);
   const state=(yield* ledger.familyStatus(common).pipe(Effect.mapError(()=>pelFailure('binding-mismatch','Fixture family unavailable')))).family.children[selected.childId]!;assert.equal(state.currentCandidate?.candidateSha256,candidate.candidateSha256);assert.ok(state.milestones.checks&&state.milestones.audit&&state.milestones.integrated);})});
  const handler=makePelPublishHandler({service,resolveInput:()=>Effect.succeed(resolved),recordPublication:makePelPublicationRecorder(ledger)}),runtime:PelRuntimePorts={...original.runtime,handlers:new Map([['fm/publish',handler]]),loadRunInputs:()=>Effect.succeed(inputs),hostEvidence:()=>Effect.gen(function*(){const state=(yield* ledger.familyStatus(common).pipe(Effect.mapError(()=>pelFailure('binding-mismatch','Fixture family unavailable')))).family.children[selected.childId]!;return {milestones:contract.requiredMilestones.filter(key=>state.milestones[key]!==undefined),receiptRefs:[]};})};
  yield* appendPelRecord(binding,'pel.run.v1',{bindingRef:yield* put(binding)});
  const provide=<A,E,R>(effect:Effect.Effect<A,E,R>)=>effect.pipe(Effect.provideService(PelRuntime,runtime));
  return {start:()=>provide(runProgram(original.context.checked,binding)),resume:()=>provide(withPelRunOwner(binding,owner=>resumeProgram(runId,{...inputs,owner}))),registerPublication:()=>ledger.registerChildAuthority(publication.registration),status:()=>Effect.map(ledger.familyStatus(common),state=>state.family.children[selected.childId]!),replay:()=>Effect.gen(function*(){const result=replayPelRun(yield* readPelRecords(runId));assert.ok(result.ok);return result.value;})};
 });
 const run=<A,E,R>(effect:Effect.Effect<A,E,R>)=>Effect.runPromise(f.provide(effect).pipe(Effect.provide(liveProcessExec),Effect.provide(makeLiveRunLease(f.root))) as Effect.Effect<A,E>);
 return {setup,run,base,head:()=>git(workspace,'rev-parse','HEAD'),indexUnchanged:()=>readFileSync(join(workspace,'.git/index')).equals(baseIndex),get commit(){return commit;},remoteObject:()=>git(f.root,'--git-dir',remote,'rev-parse','refs/heads/reviewed'),get pushes(){return pushes;},set dropAck(value:boolean){dropAck=value;},set denyObservation(value:boolean){denyObservation=value;},set mutation(value:null|'candidate'|'target'){mutation=value;},close:f.close};
}
