import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Effect} from 'effect';
import {mkdtempSync,mkdirSync,rmSync,statSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {makeLivePelNativeServices} from './pel-native-live.js';
import type {HostContextV1} from './pel-run-contract.js';
function fixture(){const root=mkdtempSync(join(tmpdir(),'pel-native-live-'));const workspace=join(root,'workspace');mkdirSync(workspace);mkdirSync(join(workspace,'.git'));mkdirSync(join(workspace,'src'));const info=statSync(workspace);const context={workspace:{canonicalRoot:workspace,directoryIdentity:`${info.dev}:${info.ino}`,grantId:'workspace',writablePaths:['src']},binding:{authoritySha256:'a'.repeat(64),repository:{gitCommonDir:join(workspace,'.git')},stateRoot:join(root,'state'),limits:{deadline:Date.now()+10000}}} as unknown as HostContextV1;const live={stateRoot:join(root,'state'),worktreeRoot:workspace,userHome:join(root,'home'),environment:{PATH:process.env.PATH,AMBIENT_SECRET:'must-not-cross'}};return {root,context,live,close:()=>rmSync(root,{recursive:true,force:true})};}
test('live native policy derives only original workspace and authority identity; API versions require no native lookup',async()=>{const f=fixture();try{const services=makeLivePelNativeServices(f.live);assert.deepEqual(services.supportedModes['grok-acp'],['native-coding']);const policy=await Effect.runPromise(services.nativePolicy(f.context));assert.match(policy.hostPermissionPortRef,/^pel-native-host-/);assert.equal(policy.permissionGrantIds.length,1);const other=await Effect.runPromise(services.nativePolicy({...f.context,binding:{...f.context.binding,authoritySha256:'b'.repeat(64)}}));assert.notEqual(policy.hostPermissionPortRef,other.hostPermissionPortRef);assert.equal(await Effect.runPromise(services.transportVersion('openai-responses',f.context)),'1');assert.equal((await Effect.runPromise(services.transportVersion('gemini-cli',f.context).pipe(Effect.either)))._tag,'Left');}finally{f.close();}});
test('live native discovery uses exact metadata argv and minimal environment; missing installation stays unsupported',async()=>{const f=fixture();try{let probes=0;const services=makeLivePelNativeServices(f.live,{which:name=>Effect.succeed(name==='grok'?process.execPath:name==='node'?process.execPath:name==='bwrap'?'/usr/bin/bwrap':null),runCaptured:request=>Effect.sync(()=>{probes++;assert.deepEqual(request.args,['--version']);assert.equal(request.env?.AMBIENT_SECRET,undefined);assert.equal(request.env?.HOME?.startsWith('/tmp/foreman-native-version-'),true);return {exitCode:0,stdout:'1.2.3\n',stderr:''};})});assert.equal(await Effect.runPromise(services.transportVersion('grok-acp',f.context)),'1.2.3');assert.equal(probes,1);assert.equal((await Effect.runPromise(services.transportVersion('claude-code',f.context).pipe(Effect.either)))._tag,'Left');}finally{f.close();}});
