import assert from 'node:assert/strict';
import {test} from 'node:test';
import {Effect} from 'effect';
import {validateDataSchema,type HostRequestV1} from '@foreman/pel';
import {foremanDataSchemasV1} from './pel-host-descriptors.js';
import {makePelResearchHandler,type AdmittedResearchBundleV1} from './pel-research-host.js';
import type {HostContextV1} from './pel-run-contract.js';
const str=(value:string)=>({tag:'string' as const,value});
const sourceRef={artifactId:'sha256-'+ 'a'.repeat(64),sha256:'a'.repeat(64),byteLength:3};
const context={checked:{snapshot:{registry:{dataSchemas:foremanDataSchemasV1},policy:{allowedCapabilities:['research.read']}}}} as unknown as HostContextV1;
const request={registryId:'fm/research',boundArguments:{id:str('research'),query:str('Fable'),bundle:str('bundle:release-sources'),limit:{tag:'number',value:5}},expectedResultSchemaId:'schema:research-result-v1'} as unknown as HostRequestV1;
const admitted:AdmittedResearchBundleV1={bundleId:'bundle:release-sources',indexRef:sourceRef,sources:[sourceRef],resources:{reads:['artifact:'+sourceRef.artifactId],writes:[]},includesExternalVault:false,query:()=>Effect.succeed({schemaVersion:1,status:'complete',bundleDigest:'b'.repeat(64),query:'Fable',results:[{id:'one',sourceLocator:'https://example.invalid/source',sourceHash:'a'.repeat(64),rawHash:'a'.repeat(64),capturedAt:'2026-09-13T00:00:00Z',claimClass:'hypothesis',freshness:'fresh',excerpt:'Fable source text',coverage:['Unsupported extraction'],wikilinks:[]}],warnings:[],optionalVault:'not-requested',graph:null})};
test('T-M6-022 research preparation returns canonical read-result with no dispatch or reservation port',async()=>{let reads=0;const handler=makePelResearchHandler({resolveBundle:()=>{reads++;return Effect.succeed(admitted);}});const result=await Effect.runPromise(handler.prepare(request,context));assert.equal(result.kind,'read-result');if(result.kind==='read-result'){assert.ok(validateDataSchema(result.value,foremanDataSchemasV1['schema:research-result-v1']!));assert.deepEqual(result.sources,[sourceRef]);assert.match(result.preparationDigest,/^[a-f0-9]{64}$/u);}assert.equal(reads,1);});
test('T-M6-022 external vault requires vault.read and invalid bundles cannot create authority',async()=>{const handler=makePelResearchHandler({resolveBundle:()=>Effect.succeed({...admitted,includesExternalVault:true})});const result=await Effect.runPromise(Effect.either(handler.prepare(request,context)));assert.equal(result._tag,'Left');if(result._tag==='Left')assert.equal(result.left.code,'capability-denied');});
test('T-M6-022 immutable host refuses uncaptured CLI observations',async()=>{
 const handler=makePelResearchHandler({resolveBundle:()=>Effect.succeed({...admitted,query:()=>admitted.query({text:'Fable',limit:5}).pipe(Effect.map(value=>({...value,status:'partial' as const,results:value.results.map(row=>({...row,capturedAt:null,observedAt:'2026-09-13T00:00:00Z',freshness:'uncaptured' as const}))})))})});
 const result=await Effect.runPromise(Effect.either(handler.prepare(request,context)));
 assert.equal(result._tag,'Left');if(result._tag==='Left')assert.equal(result.left.code,'task-output-invalid');
});
test('M6 immutable research indexes retain exactly one copy of each bound source and reject changed bytes',async()=>{const {loadPelResearchBundleInputs}=await import('./pel-research-host.js'),{researchBytes}=await import('./pel-research-context.js'),{sha256Hex}=await import('@foreman/core');const source=Buffer.from('Fable immutable source'),ref={artifactId:'sha256-'+sha256Hex(source),sha256:sha256Hex(source),byteLength:source.length},index=researchBytes({schemaVersion:1,bundleId:'bundle:release-sources',capturedAt:'2026-09-13T00:00:00Z',sources:[{id:'one',sourceLocator:'https://example.invalid/source',capturedAt:'2026-09-13T00:00:00Z',raw:{path:'source.md',sha256:ref.sha256,byteLength:ref.byteLength},clean:{path:'source.md',sha256:ref.sha256,byteLength:ref.byteLength},claimClass:'hypothesis',coverage:[]}],graph:null}),indexRef={artifactId:'sha256-'+sha256Hex(index),sha256:sha256Hex(index),byteLength:index.length};let reads=0;const project={researchBundles:{'bundle:release-sources':indexRef}},read=(r:typeof ref)=>{reads++;return Effect.succeed(r.sha256===indexRef.sha256?index:source);};const loaded=await Effect.runPromise(loadPelResearchBundleInputs(project,read));assert.equal(loaded.length,2);assert.equal(reads,2);const changed=await Effect.runPromise(Effect.either(loadPelResearchBundleInputs(project,r=>Effect.succeed(r.sha256===indexRef.sha256?index:Buffer.from('changed')))));assert.equal(changed._tag,'Left');});
test('T-M6-022 actual M4 immutable read persists its preparation digest and resumes after receipt-write interruption without reservation',async()=>{
 const {pelHostFixture}=await import('./pel-host-test-fixture.js'),{PelRuntime}=await import('./pel-run-contract.js'),{makePelResourceScope}=await import('./pel-resource-scope.js'),{executeHostEffect}=await import('./pel-effects.js'),{makePelImmutableResearchHandler}=await import('./pel-research-host.js'),{readPelRecords,pelFailure}=await import('./pel-journal.js'),{sha256Hex}=await import('@foreman/core');
 const f=pelHostFixture('(fm/research :id "r" :query "Fable" :bundle "bundle:release-sources" :limit 5)');
 try{await Effect.runPromise(f.provide(Effect.gen(function*(){const x=yield* f.setup,runId=x.context.binding.runId,source=Buffer.from('Fable immutable source'),raw=yield* x.runtime.artifacts.put(runId,source,1024,'ordinary'),file={path:'source.md',sha256:raw.sha256,byteLength:raw.byteLength},indexRef=yield* x.put({schemaVersion:1,bundleId:'bundle:release-sources',capturedAt:'2026-09-13T00:00:00Z',sources:[{id:'one',sourceLocator:'https://example.invalid/source',capturedAt:'2026-09-13T00:00:00Z',raw:file,clean:file,claimClass:'hypothesis',coverage:[]}],graph:null}),context={...x.context,project:{...x.context.project,researchBundles:{'bundle:release-sources':indexRef}}},resources=yield* makePelResourceScope({readResearchIndex:(ctx,ref,max)=>x.runtime.artifacts.get(ctx.binding.runId,ref,max).pipe(Effect.mapError(()=>({code:'artifact-missing' as const,message:'Missing research index.'})))});let interruptReceipt=true;
 const runtime={...x.runtime,resources,handlers:new Map([['fm/research',makePelImmutableResearchHandler()]]),artifacts:{...x.runtime.artifacts,put:(id:typeof runId,data:Uint8Array,max:number,protection:'ordinary'|'provider-opaque')=>Effect.gen(function*(){let value:unknown;try{value=JSON.parse(Buffer.from(data).toString('utf8'));}catch{}if(interruptReceipt&&value!==null&&typeof value==='object'&&Object.hasOwn(value,'outcome')){interruptReceipt=false;return yield* Effect.fail(pelFailure('journal-write-failed','Interrupted before receipt write.'));}return yield* x.runtime.artifacts.put(id,data,max,protection);})}};
 const run=()=>executeHostEffect(x.request,context).pipe(Effect.provideService(PelRuntime,runtime),Effect.scoped);const first=yield* Effect.either(run());assert.equal(first._tag,'Left');const before=yield* readPelRecords(runId),observations=before.filter(row=>row.type==='pel.effect.observed.v1');assert.equal(observations.length,1);assert.equal(before.filter(row=>row.type==='pel.effect.intent.v1').length,0);const originalHandler=runtime.handlers.get('fm/research')!;runtime.handlers.set('fm/research',{...originalHandler,prepare:(request,context)=>originalHandler.prepare(request,context).pipe(Effect.map(prepared=>({...prepared,preparationDigest:'e'.repeat(64)})))});const changedDigest=yield* Effect.either(run());assert.equal(changedDigest._tag,'Left');if(changedDigest._tag==='Left')assert.equal(changedDigest.left.code,'binding-mismatch');runtime.handlers.set('fm/research',originalHandler);const completed=yield* run();assert.equal(completed.kind,'settled');const after=yield* readPelRecords(runId);assert.equal(after.filter(row=>row.type==='pel.effect.observed.v1').length,1);assert.equal(after.filter(row=>row.type==='pel.effect.result.v1').length,1);assert.equal((yield* x.ledger.status(context.binding.contractId)).counts.totalActions,0);
 })));}finally{f.close();}
});
test('T-M6-022 compiled research-prepare and parallel-read use admitted assets and zero external reservations',{timeout:60000},async()=>{
 const {mkdtemp,cp,mkdir,readFile,writeFile,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join,resolve}=await import('node:path'),{spawnSync}=await import('node:child_process'),{sha256Hex}=await import('@foreman/core'),{makeLiveRunJournalLayer}=await import('@foreman/event-log'),{readPelRecords}=await import('./pel-journal.js'),{makeLiveEndstopLedgerLayer,EndstopLedger}=await import('./execution-ledger.js');
 for(const [example,fixtureId,bundles,count] of [['research-prepare.pel','m6-research-prepare',{'bundle:release-sources':'fixtures/pel-research/research-bundle.json'},1],['parallel-read.pel','m6-parallel-read',{'bundle:pel-paper':'fixtures/pel-research/pel-paper.json','bundle:model-evidence':'fixtures/pel-research/model-evidence.json'},2]] as const){const root=await mkdtemp(join(tmpdir(),'pel-research-compiled-'));try{const assetRoot=join(root,'assets'),stateRoot=join(root,'state');await cp(resolve('packages/orchestration/dist-test/assets'),assetRoot,{recursive:true});await mkdir(stateRoot);const manifest=join(root,'fixture.json');await writeFile(manifest,JSON.stringify({schemaVersion:1,assetRoot,assetManifestSha256:sha256Hex(await readFile(join(assetRoot,'manifest.json'))),fixtures:{responses:[],research:{schemaVersion:1,evidenceKind:'test-fixture',fixtureId,temporaryRoot:root,stateRoot,bindingRef:'fixture:local-v1',now:Date.now(),capabilities:['fm/research'],printDelayMs:0,failurePoint:'none',bundles}}}));const run=spawnSync(process.execPath,[resolve('packages/orchestration/dist-test/pel-cli-fixture.js'),'--fixture-manifest',manifest,'run',join(assetRoot,'examples/pel',example),'--json'],{encoding:'utf8',timeout:20000,maxBuffer:1048576});assert.equal(run.status,0,run.stderr+'\n'+run.stdout);const result=JSON.parse(run.stdout);assert.equal(result.state,'succeeded');const records=await Effect.runPromise(readPelRecords(result.runId).pipe(Effect.provide(makeLiveRunJournalLayer(stateRoot))));const runRecord=records.find(row=>row.type==='pel.run.v1')!;const bindingRef=((runRecord.payload as {data:unknown}).data as {bindingRef:{artifactId:string}}).bindingRef;const capturedBinding=JSON.parse(await readFile(join(stateRoot,'runs',result.runId,'artifacts',bindingRef.artifactId),'utf8'));assert.equal(capturedBinding.evidenceKind,'test-fixture');assert.equal(records.filter(row=>row.type==='pel.effect.intent.v1').length,0);assert.equal(records.filter(row=>row.type==='pel.effect.result.v1').length,count);const readSets:string[][]=[];for(const row of records.filter(row=>row.type==='pel.effect.observed.v1')){const ref=((row.payload as {data:unknown}).data as {observationRef:{artifactId:string}}).observationRef,observed=JSON.parse(await readFile(join(stateRoot,'runs',result.runId,'artifacts',ref.artifactId),'utf8'));if(observed.stage==='research-read'){assert.match(observed.preparationDigest,/^[a-f0-9]{64}$/u);readSets.push(observed.sources.map((source:{artifactId:string})=>'artifact:'+source.artifactId));}}assert.equal(readSets.length,count);if(count===2)assert.equal(readSets[0]!.some(id=>readSets[1]!.includes(id)),false);const state=await Effect.runPromise(Effect.flatMap(EndstopLedger,ledger=>ledger.status('fixture-contract')).pipe(Effect.provide(makeLiveEndstopLedgerLayer(stateRoot))));assert.equal(state.counts.totalActions,0);}finally{await rm(root,{recursive:true,force:true});}}
});
