/** Bounded portable research reads. All returned text is untrusted evidence. */
import {constants} from 'node:fs';
import {lstat,open,realpath,stat,opendir} from 'node:fs/promises';
import {isAbsolute,join,relative,sep,dirname,basename,normalize} from 'node:path';
import {Effect} from 'effect';
import {canonicalize,isCoreFailure,parseJsonRejectDuplicateKeys,sha256Hex} from '@foreman/core';
export const RESEARCH_BOUNDS={manifestBytes:1024*1024,sourceBytes:32*1024*1024,totalBytes:128*1024*1024,snapshotBytes:8*1024*1024,sources:512,results:20,excerptBytes:8192} as const;
export type ResearchClaimClassV1='hypothesis'|'adopted-decision'|'verified-observation'|'open-question';
export interface ResearchFailureV1 {readonly _tag:'ResearchFailure';readonly outcome:'invalid'|'failed'|'cancelled';readonly code:string;readonly message:string;}
export const researchFailure=(outcome:ResearchFailureV1['outcome'],code:string,message:string):ResearchFailureV1=>({_tag:'ResearchFailure',outcome,code,message});
export interface ResearchFileV1 {readonly path:string;readonly sha256:string;readonly byteLength:number;}
export interface ResearchSourceBindingV1 {readonly id:string;readonly sourceLocator:string;readonly capturedAt:string;readonly raw:ResearchFileV1;readonly clean:ResearchFileV1;readonly claimClass:ResearchClaimClassV1;readonly coverage:readonly string[];readonly notePath?:string;readonly excerptRange?:{readonly startByte:number;readonly endByte:number};}
export interface ResearchGraphV1 {readonly graphifyVersion:'0.9.48'|'0.9.61';readonly authority:'qualified'|'advisory';readonly sha256:string;readonly sourceCommit:string;readonly coverage:readonly string[];}
export interface ResearchBundleV1 {readonly schemaVersion:1;readonly bundleId:string;readonly capturedAt:string;readonly sources:readonly ResearchSourceBindingV1[];readonly graph:ResearchGraphV1|null;readonly includesExternalVault?:boolean;}
export interface ResearchResultV1 {readonly id:string;readonly sourceLocator:string;readonly sourceHash:string;readonly rawHash:string;readonly capturedAt:string|null;readonly observedAt?:string;readonly claimClass:ResearchClaimClassV1;readonly freshness:'fresh'|'stale'|'missing'|'uncaptured';readonly excerpt:string;readonly coverage:readonly string[];readonly noteLink?:string;readonly wikilinks:readonly string[];}
export interface ResearchContextV1 {readonly schemaVersion:1;readonly status:'complete'|'stale'|'partial';readonly bundleDigest:string;readonly query:string;readonly results:readonly ResearchResultV1[];readonly warnings:readonly string[];readonly optionalVault:'not-requested'|'present'|'missing';readonly graph:ResearchGraphV1|null;}
export interface ResearchSnapshotV1 {readonly schemaVersion:1;readonly bundleDigest:string;readonly bundle:ResearchBundleV1;readonly results:readonly ResearchResultV1[];readonly sourceRoot?:string;}
export interface ResearchReadPortV1 {readonly read:(root:string,path:string,maxBytes:number)=>Effect.Effect<Uint8Array|null,ResearchFailureV1>;readonly directory:(path:string)=>Effect.Effect<boolean,ResearchFailureV1>;readonly listNotes?:(root:string)=>Effect.Effect<readonly string[],ResearchFailureV1>;}
const object=(x:unknown):x is Record<string,unknown>=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const keys=(x:Record<string,unknown>,required:readonly string[],optional:readonly string[]=[])=>required.every(k=>Object.hasOwn(x,k))&&Object.keys(x).every(k=>required.includes(k)||optional.includes(k));
const bounded=(x:unknown,max:number):x is string=>typeof x==='string'&&x.length>0&&Buffer.byteLength(x)<=max&&!/[\u0000-\u001f\u007f]/u.test(x);
const hash=(x:unknown):x is string=>typeof x==='string'&&/^[a-f0-9]{64}$/u.test(x);
const path=(x:unknown):x is string=>bounded(x,4096)&&!isAbsolute(x)&&!x.includes('\\')&&x.split('/').every(p=>p!=='.'&&p!=='..'&&p!==''&&!['.git','.env','.harness'].includes(p))&&!/\.(pem|key|p12|pfx)$/iu.test(x);
const date=(x:unknown):x is string=>bounded(x,64)&&Number.isFinite(Date.parse(x));
const coverage=(x:unknown):x is readonly string[]=>Array.isArray(x)&&x.length<=20&&x.every(v=>bounded(v,1024));
const claim=(x:unknown):x is ResearchClaimClassV1=>['hypothesis','adopted-decision','verified-observation','open-question'].includes(String(x));
function file(x:unknown):x is ResearchFileV1{return object(x)&&keys(x,['path','sha256','byteLength'])&&path(x.path)&&hash(x.sha256)&&Number.isSafeInteger(x.byteLength)&&Number(x.byteLength)>=0&&Number(x.byteLength)<=RESEARCH_BOUNDS.sourceBytes;}
function source(x:unknown):x is ResearchSourceBindingV1{return object(x)&&keys(x,['id','sourceLocator','capturedAt','raw','clean','claimClass','coverage'],['notePath','excerptRange'])&&bounded(x.id,256)&&bounded(x.sourceLocator,4096)&&date(x.capturedAt)&&file(x.raw)&&file(x.clean)&&claim(x.claimClass)&&coverage(x.coverage)&&(x.notePath===undefined||path(x.notePath))&&(x.excerptRange===undefined||object(x.excerptRange)&&keys(x.excerptRange,['startByte','endByte'])&&Number.isSafeInteger(x.excerptRange.startByte)&&Number.isSafeInteger(x.excerptRange.endByte)&&Number(x.excerptRange.startByte)>=0&&Number(x.excerptRange.endByte)>Number(x.excerptRange.startByte)&&Number(x.excerptRange.endByte)<=x.clean.byteLength&&Number(x.excerptRange.endByte)-Number(x.excerptRange.startByte)<=8192);}
function graph(x:unknown):x is ResearchGraphV1|null{return x===null||object(x)&&keys(x,['graphifyVersion','authority','sha256','sourceCommit','coverage'])&&((x.graphifyVersion==='0.9.48'&&x.authority==='qualified')||(x.graphifyVersion==='0.9.61'&&x.authority==='advisory'))&&hash(x.sha256)&&typeof x.sourceCommit==='string'&&/^[a-f0-9]{40}$/u.test(x.sourceCommit)&&coverage(x.coverage);}
export function decodeResearchBundleV1(x:unknown):x is ResearchBundleV1{return object(x)&&keys(x,['schemaVersion','bundleId','capturedAt','sources','graph'],['includesExternalVault'])&&x.schemaVersion===1&&bounded(x.bundleId,256)&&date(x.capturedAt)&&Array.isArray(x.sources)&&x.sources.length<=RESEARCH_BOUNDS.sources&&x.sources.every(source)&&new Set(x.sources.map(s=>s.id)).size===x.sources.length&&graph(x.graph)&&(x.includesExternalVault===undefined||typeof x.includesExternalVault==='boolean');}
export function decodeResearchSnapshotV1(x:unknown):x is ResearchSnapshotV1 {
 if(!object(x)||!keys(x,['schemaVersion','bundleDigest','bundle','results'],['sourceRoot'])||x.schemaVersion!==1||!hash(x.bundleDigest)||!decodeResearchBundleV1(x.bundle)||!Array.isArray(x.results)||x.results.length!==x.bundle.sources.length||(x.sourceRoot!==undefined&&(!bounded(x.sourceRoot,4096)||!isAbsolute(x.sourceRoot)||normalize(x.sourceRoot)!==x.sourceRoot)))return false;
 const bundle=x.bundle;return x.results.every((r:unknown,index:number)=>{const binding=bundle.sources[index]!;return object(r)&&keys(r,['id','sourceLocator','sourceHash','rawHash','capturedAt','claimClass','freshness','excerpt','coverage','wikilinks'],['noteLink'])&&r.id===binding.id&&r.sourceLocator===binding.sourceLocator&&r.sourceHash===binding.clean.sha256&&r.rawHash===binding.raw.sha256&&r.capturedAt===binding.capturedAt&&r.claimClass===binding.claimClass&&['fresh','stale','missing'].includes(String(r.freshness))&&typeof r.excerpt==='string'&&Buffer.byteLength(r.excerpt)<=8192&&coverage(r.coverage)&&Array.isArray(r.wikilinks)&&r.wikilinks.length<=20&&r.wikilinks.every(v=>bounded(v,256))&&(r.noteLink===undefined||bounded(r.noteLink,8192));});
}
export function parseResearchJson(bytes:Uint8Array):unknown {const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes),value=parseJsonRejectDuplicateKeys(text);if(isCoreFailure(value))throw Error('Invalid JSON');return value;}
export const researchBytes=(value:unknown)=>Buffer.from(canonicalize(value)+'\n');
export const liveResearchReadPort:ResearchReadPortV1={
 listNotes:root=>Effect.tryPromise({try:async()=>{
  const canonical=await realpath(root),notes:string[]=[];let entries=0;
  const visit=async(directory:string,depth:number):Promise<void>=>{if(depth>16)throw Error('Vault depth bound');const canonicalDirectory=await realpath(directory);if(relative(canonical,canonicalDirectory).split(sep).includes('..'))throw Error('Vault path escape');const handle=await opendir(directory);for await(const entry of handle){if(++entries>4096)throw Error('Vault entry bound');if(entry.name.startsWith('.')||entry.isSymbolicLink())continue;const target=join(directory,entry.name),name=relative(canonical,target).split(sep).join('/');if(!path(name))continue;if(entry.isDirectory())await visit(target,depth+1);else if(entry.isFile()&&/\.md$/iu.test(entry.name)){notes.push(name);if(notes.length>128)throw Error('Vault note bound');}}};
  await visit(canonical,0);return notes.sort();
 },catch:()=>researchFailure('failed','vault-unavailable','Optional vault notes could not be read within their bounds.')}),
 directory:p=>Effect.tryPromise({try:async()=>{try{return (await stat(p)).isDirectory();}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return false;throw e;}},catch:()=>researchFailure('failed','read-failed','The optional context directory could not be read.')}),
 read:(root,name,maxBytes)=>Effect.tryPromise({try:async()=>{
  if(!path(name)||!Number.isSafeInteger(maxBytes)||maxBytes<0)throw researchFailure('invalid','invalid-path','The source path or read bound is invalid.');
  let canonical:string;try{canonical=await realpath(root);}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return null;throw e;}const target=join(canonical,name);let before;try{before=await lstat(target);}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return null;throw e;}
  const parent=await realpath(join(target,'..'));if(relative(canonical,parent).split(sep).includes('..')||before.isSymbolicLink()||!before.isFile()||before.size>maxBytes)throw researchFailure('invalid','unsafe-source','The source escapes its root, changed type, or exceeds its bound.');
  const fd=await open(target,constants.O_RDONLY|constants.O_NOFOLLOW);try{const opened=await fd.stat();if(opened.dev!==before.dev||opened.ino!==before.ino||opened.size>maxBytes)throw Error('Changed source');const content=await fd.readFile();const after=await fd.stat(),current=await lstat(target);if(content.byteLength>maxBytes||after.ino!==current.ino||after.dev!==current.dev||after.mtimeMs!==opened.mtimeMs||after.ctimeMs!==opened.ctimeMs||after.size!==opened.size)throw Error('Changed source');return content;}finally{await fd.close();}
 },catch:e=>object(e)&&e._tag==='ResearchFailure'?e as unknown as ResearchFailureV1:researchFailure('failed','read-failed','The required research input could not be read safely.')})
};
function safeExcerpt(text:string,max=RESEARCH_BOUNDS.excerptBytes):string{
 const redacted=text.replace(/<(?:think|analysis|reasoning)>[\s\S]*?<\/(?:think|analysis|reasoning)>/giu,'[private reasoning omitted]').replace(/\b(?:Bearer\s+)[A-Za-z0-9._~+/-]+=*/giu,'Bearer [redacted]').replace(/\b(?:sk-[A-Za-z0-9_-]{12,}|(?:api[_-]?key|access[_-]?token|password|secret)\s*[:=]\s*[^\s,;]+)/giu,'[redacted]');
 let result='';for(const char of redacted){if(Buffer.byteLength(result)+Buffer.byteLength(char)>max)break;result+=char;}return result;
}
export function loadResearchBundle(root:string,reader:ResearchReadPortV1=liveResearchReadPort){return Effect.gen(function*(){const data=yield* reader.read(root,'research-bundle.json',RESEARCH_BOUNDS.manifestBytes);if(!data)return yield* Effect.fail(researchFailure('failed','bundle-missing','The required portable research manifest is absent.'));let parsed:unknown;try{parsed=parseResearchJson(data);}catch{return yield* Effect.fail(researchFailure('invalid','invalid-manifest','The required research manifest is invalid JSON.'));}if(!decodeResearchBundleV1(parsed))return yield* Effect.fail(researchFailure('invalid','invalid-manifest','The required research manifest has an unsupported schema.'));return {bundle:parsed,digest:sha256Hex(data)};});}
export function inspectResearchSources(root:string,bundle:ResearchBundleV1,reader:ResearchReadPortV1=liveResearchReadPort,previous:readonly ResearchResultV1[]=[]){return Effect.gen(function*(){
 let remaining=RESEARCH_BOUNDS.totalBytes as number;const loaded=new Map<string,Uint8Array|null>(),results:ResearchResultV1[]=[];
 const read=(ref:ResearchFileV1)=>Effect.gen(function*(){if(loaded.has(ref.path))return loaded.get(ref.path)!;const value=yield* reader.read(root,ref.path,Math.min(RESEARCH_BOUNDS.sourceBytes,remaining));if(value)remaining-=value.byteLength;loaded.set(ref.path,value);return value;});
 for(const row of bundle.sources){const raw=yield* read(row.raw),clean=yield* read(row.clean),freshness=!raw||!clean?'missing':raw.byteLength!==row.raw.byteLength||clean.byteLength!==row.clean.byteLength||sha256Hex(raw)!==row.raw.sha256||sha256Hex(clean)!==row.clean.sha256?'stale':'fresh',prior=previous.find(p=>p.id===row.id&&p.sourceHash===row.clean.sha256);let excerpt=safeExcerpt(prior?.excerpt??'');
  if(freshness==='fresh'){try{excerpt=safeExcerpt(new TextDecoder('utf-8',{fatal:true}).decode(row.excerptRange?clean!.subarray(row.excerptRange.startByte,row.excerptRange.endByte):clean!));}catch{return yield* Effect.fail(researchFailure('invalid','unsupported-extraction','A clean research source is not valid UTF-8.'));}}
  results.push({id:row.id,sourceLocator:row.sourceLocator,sourceHash:row.clean.sha256,rawHash:row.raw.sha256,capturedAt:row.capturedAt,claimClass:row.claimClass,freshness,excerpt,coverage:[...row.coverage,...(freshness==='fresh'?[]:[freshness==='missing'?'Source is missing.':'Source bytes differ from their captured hash.'])].slice(0,20),wikilinks:[...excerpt.matchAll(/\[\[([^\]\n]{1,256})\]\]/gu)].slice(0,20).map(m=>m[1]!)});
 }return results;
});}
export function makePelResearchContextService(options:{readonly bundleRoot:string;readonly snapshotPath?:string;readonly reader?:ResearchReadPortV1}){
 const reader=options.reader??liveResearchReadPort;
 const view=(vault?:string)=>Effect.gen(function*(){let activeRoot=options.bundleRoot;if(options.snapshotPath){const data=yield* reader.read(dirname(options.snapshotPath),basename(options.snapshotPath),RESEARCH_BOUNDS.snapshotBytes);if(data){let parsed:unknown;try{parsed=parseResearchJson(data);}catch{return yield* Effect.fail(researchFailure('invalid','invalid-snapshot','The derived research snapshot is malformed.'));}if(!decodeResearchSnapshotV1(parsed))return yield* Effect.fail(researchFailure('invalid','invalid-snapshot','The derived research snapshot has an unsupported schema.'));activeRoot=parsed.sourceRoot??activeRoot;}}const loaded=yield* loadResearchBundle(activeRoot,reader);let previous:readonly ResearchResultV1[]=[],snapshotDigest:string|null=null;const warnings:string[]=[];
  if(options.snapshotPath){const {dirname,basename}=yield* Effect.promise(()=>import('node:path'));const data=yield* reader.read(dirname(options.snapshotPath),basename(options.snapshotPath),RESEARCH_BOUNDS.snapshotBytes);if(data){let parsed:unknown;try{parsed=parseResearchJson(data);}catch{return yield* Effect.fail(researchFailure('invalid','invalid-snapshot','The derived research snapshot is malformed.'));}if(!decodeResearchSnapshotV1(parsed))return yield* Effect.fail(researchFailure('invalid','invalid-snapshot','The derived research snapshot has an unsupported schema.'));previous=parsed.results as unknown as ResearchResultV1[];snapshotDigest=sha256Hex(data);if(parsed.bundleDigest!==loaded.digest)warnings.push('The captured bundle changed after the derived snapshot.');}
   const marker=yield* reader.read(dirname(options.snapshotPath),basename(options.snapshotPath)+'.incomplete',4096);if(marker){let value:unknown;try{value=parseResearchJson(marker);}catch{return yield* Effect.fail(researchFailure('invalid','invalid-refresh-marker','Refresh metadata is invalid.'));}if(!object(value)||!keys(value,['schemaVersion','previousSnapshotSha256'])||value.schemaVersion!==1||value.previousSnapshotSha256!==null&&!hash(value.previousSnapshotSha256))return yield* Effect.fail(researchFailure('invalid','invalid-refresh-marker','Refresh metadata is invalid.'));if(value.previousSnapshotSha256===snapshotDigest)warnings.push('The previous refresh did not complete.');}
  }
  const results=yield* inspectResearchSources(activeRoot,loaded.bundle,reader,previous);let optionalVault:ResearchContextV1['optionalVault']='not-requested';
  if(vault){const available=yield* Effect.either(reader.directory(vault));optionalVault=available._tag==='Right'&&available.right?'present':'missing';if(optionalVault==='missing')warnings.push(available._tag==='Left'?'Optional vault could not be read.':'Optional vault is absent.');else{
   for(let i=0;i<results.length;i++){const note=loaded.bundle.sources[i]?.notePath;if(note)results[i]={...results[i]!,noteLink:`obsidian://open?path=${encodeURIComponent(join(vault,note))}`};}
   if(reader.listNotes){const notes=yield* Effect.either(Effect.gen(function*(){const names=yield* reader.listNotes!(vault),rows:ResearchResultV1[]=[];let remaining=16*1024*1024;for(const name of names.slice(0,Math.min(128,RESEARCH_BOUNDS.sources-results.length))){if(!path(name)||!/\.md$/iu.test(name))return yield* Effect.fail(researchFailure('invalid','unsafe-note','Optional note path is invalid.'));const bytes=yield* reader.read(vault,name,Math.min(1024*1024,remaining));if(!bytes)continue;remaining-=bytes.byteLength;let text:string;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{return yield* Effect.fail(researchFailure('invalid','unsupported-note','Optional note is not UTF-8.'));}const excerpt=safeExcerpt(text),sourceHash=sha256Hex(bytes),noteLink=`obsidian://open?path=${encodeURIComponent(join(vault,name))}`;rows.push({id:`vault:${name}`,sourceLocator:noteLink,sourceHash,rawHash:sourceHash,capturedAt:null,observedAt:new Date().toISOString(),claimClass:'hypothesis',freshness:'uncaptured',excerpt,coverage:['Unverified external note; no execution authority.','Live note observation; no immutable capture or freshness proof.'],noteLink,wikilinks:[...excerpt.matchAll(/\[\[([^\]\n]{1,256})\]\]/gu)].slice(0,20).map(m=>m[1]!)});}return rows;}));if(notes._tag==='Left')warnings.push('Optional vault notes could not be read within their bounds.');else{results.push(...notes.right);if(results.length===RESEARCH_BOUNDS.sources)warnings.push('Optional vault coverage is limited by the source bound.');}}
  }}
  if(loaded.bundle.graph&&results.some(r=>r.freshness==='stale'||r.freshness==='missing'))warnings.push('Graph freshness is stale because captured source evidence changed or is missing.');
  if(loaded.bundle.graph?.authority==='advisory')warnings.push('The advisory graph does not carry qualified graph authority.');
  return {schemaVersion:1 as const,status:results.some(r=>r.freshness==='stale'||r.freshness==='missing')||warnings.some(w=>/changed|did not complete/u.test(w))?'stale' as const:results.some(r=>r.freshness==='uncaptured')?'partial' as const:'complete' as const,bundleDigest:loaded.digest,results,warnings,optionalVault,graph:loaded.bundle.graph};
 });
 return {query:(args:{readonly text:string;readonly limit?:number;readonly vault?:string})=>Effect.gen(function*(){const limit=args.limit??5;if(!bounded(args.text,4096)||!Number.isSafeInteger(limit)||limit<1||limit>20)return yield* Effect.fail(researchFailure('invalid','invalid-arguments','Query text and result limit exceed their bounds.'));const context=yield* view(args.vault),terms=[...new Set(args.text.toLocaleLowerCase('en-US').match(/[\p{L}\p{N}_-]+/gu)??[])];const score=(row:ResearchResultV1)=>terms.reduce((n,t)=>n+Number((row.excerpt+' '+row.sourceLocator+' '+row.id).toLocaleLowerCase('en-US').includes(t)),0);return {...context,query:args.text,results:context.results.map((row,index)=>({row,index,score:score(row)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.index-b.index).slice(0,limit).map(x=>x.row)};}),status:(args:{readonly vault?:string}={})=>view(args.vault)};
}
/** Adapt existing capture formats. Classification always comes from an explicit curated caller. */
export function normalizeCapturedResearchManifest(data:Uint8Array,metadata:{readonly claimClass:ResearchClaimClassV1;readonly coverage:readonly string[]}):{ok:true;value:readonly ResearchSourceBindingV1[]}|{ok:false;error:string}{try{
 if(data.byteLength>RESEARCH_BOUNDS.manifestBytes||!claim(metadata.claimClass)||!coverage(metadata.coverage))throw Error('Invalid bound');const manifest=parseResearchJson(data);let rows:unknown[];let capturedAt:unknown;
 if(Array.isArray(manifest))rows=manifest;else if(object(manifest)){capturedAt=manifest.archivedAt??manifest.fetched_at??manifest.captured_at;if(Array.isArray(manifest.sources))rows=manifest.sources;else if(Array.isArray(manifest.records))rows=manifest.records;else if(object(manifest.files))rows=Object.entries(manifest.files).map(([file,sha256])=>({file,sha256,url:manifest.url}));else throw Error('Unsupported capture manifest');}else throw Error('Unsupported capture manifest');
 const result=rows.map((row,index)=>{if(!object(row))throw Error('Invalid source');const rawPath=row.raw_file??row.file??row.path,cleanPath=row.clean_file??rawPath,rawHash=row.raw_sha256??row.sha256,cleanHash=row.clean_sha256??rawHash,rawBytes=row.raw_bytes??row.bytes??row.byteLength,cleanBytes=row.clean_bytes??rawBytes;
 const value={id:String(row.id??index),sourceLocator:row.source_url??row.url,capturedAt:row.captured_at??row.retrieved_at??row.captureFileModifiedAt??capturedAt,raw:{path:rawPath,sha256:rawHash,byteLength:rawBytes},clean:{path:cleanPath,sha256:cleanHash,byteLength:cleanBytes},claimClass:metadata.claimClass,coverage:[...metadata.coverage,...(cleanPath===rawPath?['No separate clean extraction is available.']:[])].slice(0,20)};
 if(!source(value))throw Error('Capture manifest needs validated byte lengths and provenance');return value;});if(result.length>RESEARCH_BOUNDS.sources)throw Error('Source bound');return {ok:true,value:result};
 }catch{return {ok:false,error:'The captured manifest is invalid or lacks bounded source provenance.'};}}
