import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,readFile,readlink,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Effect} from 'effect';
import {canonicalize} from '@foreman/core';
import {installPackage} from './pel-install.js';
import {makeLivePelAdoptionServices} from './pel-adoption.js';
import {packageFixture} from './fixtures/pel-install/package-fixture.js';
test('T-M6-017 rollback verifies retained bytes and every registered root before switching current',async()=>{const f=await packageFixture();try{await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}));const old=f.manifest;await writeFile(join(f.sourceRoot,'docs/guides/pel/install.md'),'next');const next=await f.seal('1.0.0');await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}));const a=join(f.root,'state-a'),b=join(f.root,'state-b');await mkdir(join(a,'runs'),{recursive:true});await mkdir(join(b,'runs','pending'),{recursive:true});await writeFile(join(b,'runs/pending/events.ndjson'),'unsupported checkpoint\n');const services=makeLivePelAdoptionServices({entryUrl:pathToFileURL(join(f.prefix,'versions',next.buildId,'runtime/dist/foreman.js')).href,foremanHome:f.root,loadRegisteredRoots:()=>Effect.succeed([a,b])});assert.equal((await Effect.runPromise(services.version())).buildId,next.buildId);const refused=await Effect.runPromise(services.rollback(old.buildId).pipe(Effect.either));assert.equal(refused._tag,'Left');if(refused._tag==='Left')assert.equal(refused.left.exitCode,3);assert.equal(await readlink(join(f.prefix,'current')),`versions/${next.buildId}`);await writeFile(join(b,'runs/pending/events.ndjson'),'');const restored=await Effect.runPromise(services.rollback(old.buildId));assert.equal(restored.buildId,old.buildId);assert.equal(await readlink(join(f.prefix,'current')),`versions/${old.buildId}`);const absent=await Effect.runPromise(services.rollback('f'.repeat(64)).pipe(Effect.either));assert.equal(absent._tag,'Left');if(absent._tag==='Left')assert.equal(absent.left.exitCode,2);}finally{await f.close();}});
test('T-M6-018 support export writes only the safe projection and reports unknown runs without output',async()=>{const f=await packageFixture();try{const services=makeLivePelAdoptionServices({entryUrl:pathToFileURL(join(f.sourceRoot,'runtime/dist/foreman.js')).href,foremanHome:f.root,loadSupportRun:id=>id==='known'?Effect.succeed({events:[],result:{rawPrompt:'SECRET'}}):Effect.fail({_tag:'PelAdoptionFailure',code:'UnknownRun',message:'Unknown run.',exitCode:2})});const out=join(f.root,'support.json');await Effect.runPromise(services.support('known',out));const text=await readFile(out,'utf8');assert.equal(text.includes('SECRET'),false);assert.equal(JSON.parse(text).evidenceKind,'unknown');assert.equal(JSON.parse(text).reproductionCommand,'foreman status known --json');const missing=await Effect.runPromise(services.support('missing',join(f.root,'missing.json')).pipe(Effect.either));assert.equal(missing._tag,'Left');if(missing._tag==='Left')assert.equal(missing.left.exitCode,2);}finally{await f.close();}});

import {pelHostFixture} from './pel-host-test-fixture.js';
import {checkPelRollbackRoots} from './pel-adoption.js';
import {createDefaultAuthoringSnapshotV1} from './pel-host-descriptors.js';
test('T-M6-017 equal numeric schema versions do not admit a different active registry or handler',async()=>{const f=await packageFixture(),run=pelHostFixture('(fm/checkpoint "pending")');try{await Effect.runPromise(run.provide(run.setup));const path=join(run.root,'runs/host-run/events.ndjson'),before=await readFile(path),snapshot=createDefaultAuthoringSnapshotV1();await Effect.runPromise(checkPelRollbackRoots([run.root],f.manifest,snapshot));for(const [manifest,target]of [[f.manifest,{...snapshot,registryDigest:'f'.repeat(64)}],[{...f.manifest,runtimeCompatibility:{runtimeVersion:'1',runtimeHandlerVersion:'older'}},snapshot]] as const){const failure=await Effect.runPromise(checkPelRollbackRoots([run.root],manifest,target).pipe(Effect.either));assert.equal(failure._tag,'Left');if(failure._tag==='Left')assert.equal(failure.left.exitCode,3);}assert.deepEqual(await readFile(path),before);}finally{run.close();await f.close();}});

test('T-M6-018 support refuses an existing output and cancellation leaves no output',async()=>{const f=await packageFixture();try{const out=join(f.root,'existing.json');await writeFile(out,'original');const services=makeLivePelAdoptionServices({entryUrl:pathToFileURL(join(f.sourceRoot,'runtime/dist/foreman.js')).href,foremanHome:f.root,loadSupportRun:()=>Effect.succeed({events:[],result:null})});const refused=await Effect.runPromise(services.support('known',out).pipe(Effect.either));assert.equal(refused._tag,'Left');if(refused._tag==='Left')assert.equal(refused.left.exitCode,1);assert.equal(await readFile(out,'utf8'),'original');const controller=new AbortController(),blocked=makeLivePelAdoptionServices({entryUrl:pathToFileURL(join(f.sourceRoot,'runtime/dist/foreman.js')).href,foremanHome:f.root,loadSupportRun:()=>Effect.never}),promise=Effect.runPromise(blocked.support('known',join(f.root,'cancelled.json')),{signal:controller.signal});controller.abort();await assert.rejects(promise);await assert.rejects(readFile(join(f.root,'cancelled.json')));}finally{await f.close();}});

test('T-M6-018 live export resolves an actual retained run through the original project registry',async()=>{const f=await packageFixture(),run=pelHostFixture('(fm/checkpoint "pending")');try{await Effect.runPromise(run.provide(run.setup));await writeFile(join(f.root,'projects.json'),canonicalize({schema:'foreman.project-registry.v1',generation:1,projects:[{project_id:'00000000-0000-4000-8000-000000000001',operation_id:'00000000-0000-4000-8000-000000000002',generation:1,git_common_dir:run.root,worktree_paths:[run.root],store_backend:'files-only',store_location:run.root,state:'active'}]})+'\n',{mode:0o600});const services=makeLivePelAdoptionServices({entryUrl:pathToFileURL(join(f.sourceRoot,'runtime/dist/foreman.js')).href,foremanHome:f.root});const result=await Effect.runPromise(services.support('host-run',join(f.root,'retained.json')));const bundle=JSON.parse(await readFile(result.out,'utf8'));assert.equal(bundle.runId,'host-run');assert.equal(bundle.evidenceKind,'test-fixture');assert.ok(bundle.eventIds.length>=2);assert.equal(bundle.version.buildId,f.manifest.buildId);const unknown=await Effect.runPromise(services.support('absent',join(f.root,'absent.json')).pipe(Effect.either));assert.equal(unknown._tag,'Left');if(unknown._tag==='Left')assert.equal(unknown.left.exitCode,2);}finally{run.close();await f.close();}});

import {checkPel,createPelEnvironment,startPel,encodePelContinuation} from '@foreman/pel';
import {appendPelRecord} from './pel-journal.js';
test('T-M6-017 a terminal result before a revision cannot hide the new active checkpoint',async()=>{const f=await packageFixture(),run=pelHostFixture('(fm/checkpoint "old")');try{await Effect.runPromise(run.provide(Effect.gen(function*(){const original=yield* run.setup,binding=original.context.binding,snapshot=original.context.checked.snapshot;const source=Buffer.from('(fm/checkpoint "revised")'),checked=checkPel({source,snapshot});assert.equal(checked.tag,'ok');if(checked.tag!=='ok')throw Error('checked');const revised={...binding,checkedProgramDigest:checked.checked.bindingDigest,revisionDigest:checked.checked.sourceDigest,sourceDigest:checked.checked.sourceDigest,artifacts:{...binding.artifacts,source:yield* original.runtime.artifacts.put(binding.runId,source,65536,'ordinary')}};const step=startPel(checked.checked.program,createPelEnvironment(snapshot.registry),snapshot.limits,snapshot.options);assert.equal(step.tag,'suspend');if(step.tag!=='suspend')throw Error('step');yield* appendPelRecord(binding,'pel.run-result.v1',{resultRef:yield* original.put({schemaVersion:1,runId:binding.runId,state:'failed',externalOutcome:'none',updatedAt:original.now,programDigest:binding.checkedProgramDigest,attempt:binding.attempt,finalValue:null,artifacts:[],receipts:[],outputs:[],usage:{observed:{},reservedCostUsd:0,unresolvedEffectIds:[],counters:step.counters},diagnostics:[]})});yield* appendPelRecord(binding,'pel.revision.v1',{bindingRef:yield* original.put(revised),decisionRef:yield* original.put({evidenceKind:'test-fixture',purpose:'read-only version compatibility'})});const encoded=encodePelContinuation(step.continuation);assert.ok(encoded.ok);const continuationRef=yield* original.runtime.artifacts.put(binding.runId,encoded.value,64*1024*1024,'ordinary');yield* appendPelRecord(revised,'pel.suspension.v1',{suspensionRef:yield* original.put({continuationRef,options:revised.options,optionsDigest:revised.optionsDigest,committedCounters:step.counters,pending:[],childRecordSequences:[]})});})));const snapshot=createDefaultAuthoringSnapshotV1(),path=join(run.root,'runs/host-run/events.ndjson'),before=await readFile(path);await Effect.runPromise(checkPelRollbackRoots([run.root],f.manifest,snapshot));const refused=await Effect.runPromise(checkPelRollbackRoots([run.root],f.manifest,{...snapshot,registryDigest:'f'.repeat(64)}).pipe(Effect.either));assert.equal(refused._tag,'Left');if(refused._tag==='Left')assert.equal(refused.left.exitCode,3);assert.deepEqual(await readFile(path),before);}finally{run.close();await f.close();}});

test('T-M6-018 an absent original project registry has no known runs and is not created by export',async()=>{const f=await packageFixture();try{const home=join(f.root,'unused-home'),services=makeLivePelAdoptionServices({entryUrl:pathToFileURL(join(f.sourceRoot,'runtime/dist/foreman.js')).href,foremanHome:home});const result=await Effect.runPromise(services.support('missing',join(f.root,'missing.json')).pipe(Effect.either));assert.equal(result._tag,'Left');if(result._tag==='Left')assert.equal(result.left.exitCode,2);await assert.rejects(readFile(join(home,'projects.json')));}finally{await f.close();}});

test('T-M6-017 suspended and cancel-requested durable results remain active for rollback',async()=>{
 const f=await packageFixture();try{for(const state of ['suspended','cancel-requested'] as const){const run=pelHostFixture('(fm/checkpoint "pending")');try{
  await Effect.runPromise(run.provide(Effect.gen(function*(){const v=yield* run.setup,b=v.context.binding,s=v.context.checked.snapshot,step=startPel(v.context.checked.program,createPelEnvironment(s.registry),s.limits,s.options);
   yield* appendPelRecord(b,'pel.run-result.v1',{resultRef:yield* v.put({schemaVersion:1,runId:b.runId,state,externalOutcome:'none',updatedAt:v.now,programDigest:b.checkedProgramDigest,attempt:b.attempt,finalValue:null,artifacts:[],receipts:[],outputs:[],usage:{observed:{providerCounters:{}},reservedCostUsd:0,unresolvedEffectIds:[],counters:step.counters},diagnostics:[]})});
  })));
  const result=await Effect.runPromise(checkPelRollbackRoots([run.root],{...f.manifest,runtimeCompatibility:{runtimeVersion:'1',runtimeHandlerVersion:'older'}},createDefaultAuthoringSnapshotV1()).pipe(Effect.either));assert.equal(result._tag,'Left',state);if(result._tag==='Left')assert.equal(result.left.exitCode,3);
 }finally{run.close();}}}finally{await f.close();}
});

import {withPelRegistryTransaction} from './pel-registry-transaction.js';
import {withInstalledPrefix} from './pel-install.js';
test('T-M6-017 registry and prefix transaction failures are I/O refusals before compatibility inspection',async()=>{
 const f=await packageFixture();try{
  await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}));const previous=f.manifest;
  await writeFile(join(f.sourceRoot,'docs/guides/pel/install.md'),'current candidate');const current=await f.seal('1.0.0');await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}));
  const foremanHome=join(f.root,'home');let inspections=0;
  const options={entryUrl:pathToFileURL(join(f.prefix,'versions',current.buildId,'runtime/dist/foreman.js')).href,foremanHome,loadRegisteredRoots:()=>Effect.sync(()=>{inspections++;return [];})};
  const services=makeLivePelAdoptionServices(options);
  const blocked=await Effect.runPromise(withPelRegistryTransaction(foremanHome,services.rollback(previous.buildId).pipe(Effect.either)));
  assert.equal(blocked._tag,'Left');if(blocked._tag==='Left'){assert.equal(blocked.left.code,'InstallIoFailure');assert.equal(blocked.left.exitCode,1);}assert.equal(inspections,0);assert.equal(await readlink(join(f.prefix,'current')),`versions/${current.buildId}`);
  const prefixBusy=await Effect.runPromise(withInstalledPrefix(f.prefix,false,()=>services.rollback(previous.buildId).pipe(Effect.either)));
  assert.equal(prefixBusy._tag,'Left');if(prefixBusy._tag==='Left'){assert.equal(prefixBusy.left.code,'InstallIoFailure');assert.equal(prefixBusy.left.exitCode,1);}assert.equal(inspections,0);
  const unavailableHome=join(f.root,'regular-file');await writeFile(unavailableHome,'retained');
  const unavailable=await Effect.runPromise(makeLivePelAdoptionServices({...options,foremanHome:unavailableHome}).rollback(previous.buildId).pipe(Effect.either));
  assert.equal(unavailable._tag,'Left');if(unavailable._tag==='Left'){assert.equal(unavailable.left.code,'InstallIoFailure');assert.equal(unavailable.left.exitCode,1);}assert.equal(inspections,0);assert.equal(await readFile(unavailableHome,'utf8'),'retained');assert.equal(await readlink(join(f.prefix,'current')),`versions/${current.buildId}`);
  const restored=await Effect.runPromise(services.rollback(previous.buildId));assert.equal(restored.buildId,previous.buildId);assert.equal(inspections,1);
 }finally{await f.close();}
});
