import {test} from 'node:test';
import assert from 'node:assert/strict';
import type {StoredEvent} from '@foreman/event-log';
import {projectPelSupportBundle} from './pel-support.js';
const version={releaseName:'Return of the ForeDi' as const,version:null,buildId:'a'.repeat(64)},platform={platform:'linux',arch:'x64',nodeVersion:'24.18.1'};
test('T-M6-018 support projection retains exact safe identities and event references without raw nested provider data',()=>{
 const secret='Bearer SECRET_VALUE_NEVER_EXPORT',reasoning='OPAQUE_HIDDEN_REASONING_NEVER_EXPORT',identity={kind:'native',provider:'openai',profileId:'gpt-6-astra',transportId:'codex-app-server',credentialProfileRef:secret,protocolVersion:'v2',sessionId:secret};
 const events:StoredEvent[]=[{seq:3,ts:'2026-09-13T00:00:00Z',type:'pel.effect.observed.v1',lane:'pel',payload:{schemaVersion:1,data:{providerIdentity:identity,effectId:'pel-'+ 'b'.repeat(64),observationRef:{artifactId:reasoning},authorization:secret,prompt:secret}}}];
 const input={version,platform,runId:'pel-support-run',events,result:{diagnostics:[{code:'provider-failure',message:secret,nextAction:secret,cause:{providerFailure:{_tag:'ModelMismatch',message:secret,reasoning}}}],reasoning,api_key:secret}};
 const projected=projectPelSupportBundle(input),text=JSON.stringify(projected);assert.equal(text.includes(secret),false);assert.equal(text.includes(reasoning),false);assert.match(text,/gpt-6-astra/);assert.match(text,/codex-app-server/);assert.match(text,/provider-failure/);assert.deepEqual(projected.eventIds,[3]);assert.deepEqual(projectPelSupportBundle(input),projected);assert.equal(projected.reproductionCommand,'foreman status pel-support-run --json');
});
test('T-M6-018 malicious diagnostic codes and forged provider identifiers cannot become exported payload text',()=>{
 const secret='SECRET_UNTRUSTED_DIAGNOSTIC';const projected=projectPelSupportBundle({version,platform,runId:'pel-support-run',events:[{seq:1,ts:'2026-09-13T00:00:00Z',type:'pel.effect.observed.v1',lane:'pel',payload:{data:{providerIdentity:{profileId:secret,transportId:secret,provider:secret},secret}}}],result:{diagnostics:[{code:secret,message:secret}],nested:{reasoning:secret},__proto__:{token:secret}}});assert.equal(JSON.stringify(projected).includes(secret),false);assert.deepEqual(projected.providers,[]);
});
test('T-M6-018 opaque provider revision strings are omitted instead of exposing arbitrary provider text',()=>{const secret='SECRET_PROTOCOL_VALUE';const projected=projectPelSupportBundle({version,platform,runId:'pel-support-run',events:[{seq:1,ts:'2026-09-13T00:00:00Z',type:'pel.effect.observed.v1',lane:'pel',payload:{data:{providerIdentity:{kind:'native',provider:'openai',profileId:'gpt-6-astra',transportId:'codex-app-server',protocolVersion:secret}}}}],result:{}});assert.equal(JSON.stringify(projected).includes(secret),false);});
test('T-M6-018 package identity never upgrades fixture or unavailable run provenance',()=>{for(const evidenceKind of ['product','test-fixture','unknown'] as const){const result=projectPelSupportBundle({version,platform,runId:'pel-support-run',events:[],result:{evidenceKind:'product'},evidenceKind});assert.equal(result.evidenceKind,evidenceKind);}const unavailable=projectPelSupportBundle({version,platform,runId:'pel-support-run',events:[],result:{evidenceKind:'product'}});assert.equal(unavailable.evidenceKind,'unknown');});
