import assert from 'node:assert/strict';
import {test} from 'node:test';
import {Effect} from 'effect';
import {makePublicationIntegrationFixture} from './pel-publication-integration-fixture.js';

test('T-M5-011 T-M5-012 real V2 publication waits without charge, then publishes once after exact authority registration',async()=>{
 const f=makePublicationIntegrationFixture();try{await f.run(Effect.gen(function*(){const x=yield* f.setup;const first=yield* x.start();assert.equal(first.state,'needs-action');assert.equal(first.externalOutcome,'none');assert.equal(f.pushes,0);assert.equal(f.remoteObject(),f.base);const before=yield* x.status();assert.equal(before.counts.publish,0);assert.equal(before.counts.integrate,1);assert.equal((yield* x.replay()).results.size,0);yield* x.registerPublication();const completed=yield* x.resume();assert.equal(completed.state,'succeeded',JSON.stringify(completed));assert.equal(f.pushes,1);assert.equal(f.remoteObject(),f.commit);const after=yield* x.status();assert.equal(after.counts.publish,1);assert.equal(after.counts.integrate,1);for(const action of ['implement','verify','audit','correct','integrate'] as const)assert.equal(after.counts[action],before.counts[action]);assert.equal(after.counts.totalActions,before.counts.totalActions+1);assert.equal(after._tag,'Completed');assert.ok(after.milestones.published);assert.equal((yield* x.replay()).results.size,1);}));}finally{f.close();}
});
test('T-M5-013 real V2 lost acknowledgement stays pending until observation and never republishes',async()=>{
 const f=makePublicationIntegrationFixture();try{await f.run(Effect.gen(function*(){const x=yield* f.setup;yield* x.registerPublication();f.dropAck=true;const first=yield* x.start();assert.equal(first.state,'needs-action');assert.equal(first.externalOutcome,'unknown');assert.equal(f.pushes,1);assert.equal(f.remoteObject(),f.commit);assert.equal((yield* x.replay()).results.size,0);f.denyObservation=true;const waiting=yield* x.resume();assert.equal(waiting.state,'needs-action');assert.equal(waiting.externalOutcome,'unknown');assert.equal(f.pushes,1);assert.equal((yield* x.replay()).results.size,0);f.denyObservation=false;const completed=yield* x.resume();assert.equal(completed.state,'succeeded',JSON.stringify(completed));assert.equal(f.pushes,1);assert.equal((yield* x.status()).counts.publish,1);assert.equal((yield* x.replay()).results.size,1);}));}finally{f.close();}
});

test('T-M5-012 real V2 prepared candidate or destination mutation fails before the Git publication command',async()=>{
 for(const mutation of ['candidate','target'] as const){const f=makePublicationIntegrationFixture({deferredAuthority:true,syntheticCapture:true});try{await f.run(Effect.gen(function*(){const x=yield* f.setup;yield* x.registerPublication();f.mutation=mutation;const failed=yield* x.start();assert.equal(failed.state,'failed',JSON.stringify(failed));assert.equal(f.pushes,0);assert.equal((yield* x.status()).counts.publish,1);assert.equal((yield* x.status()).counts.integrate,1);assert.ok(failed.diagnostics.some(item=>item.code===(mutation==='candidate'?'candidate-changed':'publication-authority-invalid')),JSON.stringify(failed.diagnostics));}));}finally{f.close();}}
});

test('T-M5-011 a destination admitted before candidate creation resolves later exact V2 publication authority',async()=>{
 const f=makePublicationIntegrationFixture({deferredAuthority:true});try{await f.run(Effect.gen(function*(){const x=yield* f.setup;const waiting=yield* x.start();assert.equal(waiting.state,'needs-action');assert.equal((yield* x.status()).counts.publish,0);assert.equal(f.pushes,0);yield* x.registerPublication();const completed=yield* x.resume();assert.equal(completed.state,'succeeded',JSON.stringify(completed));assert.equal((yield* x.status()).counts.publish,1);assert.equal(f.remoteObject(),f.commit);assert.equal(f.pushes,1);}));}finally{f.close();}
});


test('T-M5-011 T-M5-012 T-M5-013 real V2 synthetic captured candidate waits for deferred authority and recovers lost acknowledgement with one push',async()=>{
 const f=makePublicationIntegrationFixture({deferredAuthority:true,syntheticCapture:true});try{await f.run(Effect.gen(function*(){const x=yield* f.setup;assert.equal(f.head(),f.base);assert.ok(f.indexUnchanged());assert.notEqual(f.commit,f.base);const first=yield* x.start();assert.equal(first.state,'needs-action');assert.equal(first.externalOutcome,'none');assert.equal((yield* x.status()).counts.publish,0);assert.equal(f.pushes,0);yield* x.registerPublication();f.dropAck=true;const lost=yield* x.resume();assert.equal(lost.state,'needs-action',JSON.stringify(lost));assert.equal(lost.externalOutcome,'unknown');assert.equal(f.pushes,1);assert.equal(f.remoteObject(),f.commit);f.denyObservation=true;const pending=yield* x.resume();assert.equal(pending.state,'needs-action');assert.equal(pending.externalOutcome,'unknown');assert.equal(f.pushes,1);f.denyObservation=false;const done=yield* x.resume();assert.equal(done.state,'succeeded',JSON.stringify(done));assert.equal((yield* x.status()).counts.publish,1);assert.equal(f.pushes,1);assert.equal(f.head(),f.base);assert.ok(f.indexUnchanged());assert.equal((yield* x.replay()).results.size,1);}));}finally{f.close();}
});
