import assert from 'node:assert/strict';
import {test} from 'node:test';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,writeFileSync,rmSync,statSync,realpathSync,renameSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Effect} from 'effect';
import {canonicalize,sha256Hex} from '@foreman/core';
import type {RegisteredReleaseAuthorityV1,ReleaseEvidenceBundleV1} from '@foreman/policy';
import {ProcessExec,liveProcessExec} from './queue-services.js';
import {EndstopLedger,type ExecutionFamilyLedgerStatusV2} from './execution-ledger.js';
import {makePelPublicationService,type PelPublicationInputV1,type PreparedPelPublicationV1} from './pel-publication-service.js';
import {makePelResourceScope} from './pel-resource-scope.js';
import {PelRuntime,type HostContextV1,type PelRuntimePorts,type PreparedHostEffectV1,type PelReservationTokenV1} from './pel-run-contract.js';
import {pelHash,stablePelReservationId} from './pel-journal.js';

const git=(cwd:string,...args:string[])=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
const fileBytes=(value:unknown)=>Buffer.from(`${canonicalize(value)}\n`);
function fixture(options:{deferred?:boolean;hashRead?:'missing'|'wrong';ambiguous?:boolean}={}){
 const root=realpathSync(mkdtempSync(join(tmpdir(),'pel-publish-'))),workspace=join(root,'work'),remote=join(root,'remote.git');git(root,'init','--quiet',workspace);git(workspace,'config','user.name','Fixture');git(workspace,'config','user.email','fixture@example.invalid');writeFileSync(join(workspace,'file.ts'),'export const value = 1;\n');git(workspace,'add','.');git(workspace,'commit','--quiet','-m','base');const base=git(workspace,'rev-parse','HEAD');git(root,'init','--quiet','--bare',remote);git(workspace,'push','--quiet',remote,`${base}:refs/heads/reviewed`);writeFileSync(join(workspace,'file.ts'),'export const value = 2;\n');git(workspace,'add','.');git(workspace,'commit','--quiet','-m','candidate');const commit=git(workspace,'rev-parse','HEAD'),tree=git(workspace,'rev-parse','HEAD^{tree}'),candidate={commit,tree,candidateSha256:sha256Hex(commit)},stat=statSync(workspace);
 const design={schema:'foreman.design-approval.v1' as const,program:'v040' as const,packageId:'project-registry',designCommit:base,designTree:git(workspace,'rev-parse',`${base}^{tree}`),approvedOpenSpecSha256:'a'.repeat(64),taskPlanSha256:'b'.repeat(64),approvalStatementSha256:'c'.repeat(64),issuedAt:'2026-09-13T00:00:00Z'},audit={schema:'foreman.release-audit.v1' as const,program:'v040' as const,packageId:'project-registry',candidate,verdict:'APPROVED' as const,findings:[],evidenceSha256:'d'.repeat(64),issuedAt:design.issuedAt};
 const bundle:ReleaseEvidenceBundleV1={schema:'foreman.release-evidence-bundle.v1',program:'v040',rootContractId:'root',rootContractSha256:'a'.repeat(64),familySha256:'b'.repeat(64),childId:'v040-t2-project-registry',packageId:'project-registry',action:'publish',candidate,taskPlanSha256:design.taskPlanSha256,receipts:[design,audit],issuedAt:design.issuedAt},bytes=fileBytes(bundle),authorityRef={artifactId:`sha256-${sha256Hex(bytes)}`,sha256:sha256Hex(bytes),byteLength:bytes.length};
 const registration:RegisteredReleaseAuthorityV1={rootContractId:bundle.rootContractId,rootContractSha256:bundle.rootContractSha256,familySha256:bundle.familySha256,childId:bundle.childId,action:'publish',effectiveAction:'publish',priorReservationId:null,originReservationId:null,candidate,taskPlanSha256:bundle.taskPlanSha256,bundleSha256:authorityRef.sha256,receiptSchemas:bundle.receipts.map(row=>row.schema),receiptSha256s:bundle.receipts.map(row=>sha256Hex(fileBytes(row))),evaluationManifestSha256:null,registeredAt:design.issuedAt};
 const destination={operation:'publish' as const,repositoryIdentitySha256:'e'.repeat(64),remoteIdentity:remote,ref:'refs/heads/reviewed',expectedOldObject:{kind:'exact' as const,oid:base},authorityRef:options.deferred?null:authorityRef};
 const input:PelPublicationInputV1={destinationId:'reviewed',candidate,evidenceRefs:[{artifactId:'sha256-'+ 'f'.repeat(64),sha256:'f'.repeat(64),byteLength:1}],integrationReceiptRef:null};
 const context={effect:{effectId:'effect',requestId:'request',runId:'run',checkedDigest:'f'.repeat(64),retryOrdinal:0},binding:{runId:'run',contractId:'root',contractSha256:bundle.rootContractSha256,checkedProgramDigest:'f'.repeat(64),authoritySha256:'c'.repeat(64),authority:{kind:'v2-child',authoritySha256:'c'.repeat(64),authorityRef,rootContractId:'root',rootContractSha256:bundle.rootContractSha256,familySha256:bundle.familySha256,childId:bundle.childId,originReservationId:'origin',taskPlanSha256:bundle.taskPlanSha256,authorityBundleSha256:authorityRef.sha256},requiredMilestones:[],limits:{deadline:Date.now()+60000,maxOutputBytes:65536}},workspace:{canonicalRoot:workspace,directoryIdentity:`${stat.dev}:${stat.ino}`,repository:{gitCommonDir:join(workspace,'.git'),identitySha256:destination.repositoryIdentitySha256},writablePaths:['.']},project:{destinations:{reviewed:destination},repository:{gitCommonDir:join(workspace,'.git'),identitySha256:destination.repositoryIdentitySha256}}} as unknown as HostContextV1;
 let authorized=true,authorityValid=true,evidenceValid=true,pushes=0,dropAck=false,denyObserve=false;
 const setup=Effect.gen(function*(){const process=yield* ProcessExec,resources=yield* makePelResourceScope();const ledger={familyStatus:()=>Effect.succeed({root:{contractSha256:bundle.rootContractSha256,contract:{authorizationSha256:context.binding.authoritySha256}},family:{children:{[bundle.childId]:{currentCandidate:candidate}}},childAuthorities:authorized?(options.ambiguous?[registration,{...registration,bundleSha256:'9'.repeat(64)}]:[registration]):[]} as unknown as ExecutionFamilyLedgerStatusV2),executeChild:()=>Effect.die('Publication must not reserve twice')};
 const service=makePelPublicationService({ledger,processExec:{...process,runCaptured:options=>Effect.gen(function*(){if(options.args.includes('push')){pushes++;const result=yield* process.runCaptured(options);if(dropAck)return yield* Effect.fail({_tag:'ProcessFailure' as const,reason:'timeout' as const});return result;}if(denyObserve&&options.args.includes('ls-remote'))return yield* Effect.fail({_tag:'ProcessFailure' as const,reason:'timeout' as const});return yield* process.runCaptured(options);})},readAuthority:()=>Effect.succeed(authorityValid?bytes:Buffer.from("forged")),readAuthorityHash:()=>options.hashRead==='missing'?Effect.fail({code:'publication-authority-invalid',message:'Registered bytes unavailable.'}):Effect.succeed({ref:options.hashRead==='wrong'?{...authorityRef,sha256:'8'.repeat(64)}:authorityRef,bytes}),validateEvidence:()=>evidenceValid?Effect.void:Effect.fail({code:'publication-authority-invalid',message:'Current evidence changed.'})});
 return {service,runtime:{resources,clock:{now:Effect.sync(Date.now),sleep:Effect.sleep}} as PelRuntimePorts};});
 const run=<A,E,R>(body:(service:ReturnType<typeof makePelPublicationService>)=>Effect.Effect<A,E,R>)=>Effect.runPromise(setup.pipe(Effect.flatMap(({service,runtime})=>body(service).pipe(Effect.provideService(PelRuntime,runtime))),Effect.provide(liveProcessExec),Effect.scoped) as Effect.Effect<A,E>);
 const dispatch=(prepared:PreparedPelPublicationV1)=>{const host:Extract<PreparedHostEffectV1,{kind:'dispatch'}>={kind:'dispatch',action:'publish',operationDigest:prepared.operationDigest,resources:{reads:[],writes:[],unknownScope:workspace},inputs:authorityRef,candidate};const reservationId=stablePelReservationId(context.effect.effectId,'publish',pelHash(host));const token:PelReservationTokenV1={schemaVersion:1,kind:'v2-child',effect:context.effect,preparationDigest:pelHash(host),operationDigest:host.operationDigest,authoritySha256:context.binding.authoritySha256,reservationId,candidate,rootContractId:'root',rootContractSha256:bundle.rootContractSha256,familySha256:bundle.familySha256,childId:bundle.childId,operation:{_tag:'ReserveAction',reservationId,reservationAction:'publish',effectiveAction:'publish',originReservationId:reservationId,candidate,taskPlanSha256:bundle.taskPlanSha256,authorityBundleSha256:authorityRef.sha256}};return {host,token};};
 return {root,workspace,remote,base,candidate,input,context,run,dispatch,get pushes(){return pushes;},set authorized(value:boolean){authorized=value;},set authorityValid(value:boolean){authorityValid=value;},set evidenceValid(value:boolean){evidenceValid=value;},set dropAck(value:boolean){dropAck=value;},set denyObserve(value:boolean){denyObserve=value;},cleanup:()=>rmSync(root,{recursive:true,force:true})};
}
test('T-M5-011 missing registered authority prepares needs-action with no publication',async()=>{const f=fixture();try{f.authorized=false;await f.run(service=>Effect.gen(function*(){const result=yield* service.prepare(f.input,f.context);assert.equal(result.kind,'needs-action');assert.equal(f.pushes,0);assert.equal(git(f.root,'--git-dir',f.remote,'rev-parse','refs/heads/reviewed'),f.base);}));}finally{f.cleanup();}});
test('T-M5-012 publication consumes its one token and updates only the admitted ref',async()=>{const f=fixture();try{await f.run(service=>Effect.gen(function*(){const result=yield* service.prepare(f.input,f.context);assert.equal(result.kind,'ready');if(result.kind!=='ready')return;const {host,token}=f.dispatch(result.preparation),observed=yield* service.commit(result.preparation,host,token,f.context);assert.equal(observed.kind,'published');assert.equal(f.pushes,1);assert.equal(git(f.root,'--git-dir',f.remote,'rev-parse','refs/heads/reviewed'),f.candidate.commit);assert.equal(git(f.workspace,'rev-parse','HEAD'),f.candidate.commit);}));}finally{f.cleanup();}});
test('T-M5-012 changed candidate, target, evidence, and token fail before publication',async()=>{for(const mutation of ['candidate','target','evidence','token'] as const){const f=fixture();try{await f.run(service=>Effect.gen(function*(){const result=yield* service.prepare(f.input,f.context);if(result.kind!=='ready')throw Error('prepare');const {host,token}=f.dispatch(result.preparation);if(mutation==='candidate')writeFileSync(join(f.workspace,'file.ts'),'changed after preparation\n');if(mutation==='target')git(f.root,'--git-dir',f.remote,'update-ref','-d','refs/heads/reviewed');if(mutation==='evidence')f.evidenceValid=false;const outcome=yield* Effect.either(service.commit(result.preparation,host,mutation==='token'?{...token,operationDigest:'0'.repeat(64)}:token,f.context));assert.equal(outcome._tag,'Left');assert.equal(f.pushes,0);}));}finally{f.cleanup();}}});
test('T-M5-013 lost acknowledgement observes the exact ref without another publication',async()=>{const f=fixture();try{await f.run(service=>Effect.gen(function*(){const prepared=yield* service.prepare(f.input,f.context);if(prepared.kind!=='ready')throw Error('prepare');const {host,token}=f.dispatch(prepared.preparation);f.dropAck=true;const result=yield* service.commit(prepared.preparation,host,token,f.context);assert.equal(result.kind,'unknown');f.denyObserve=true;assert.equal((yield* service.observe(prepared.preparation,f.context)).kind,'unknown');f.denyObserve=false;assert.equal((yield* service.observe(prepared.preparation,f.context)).kind,'published');assert.equal(f.pushes,1);}));}finally{f.cleanup();}});
test('T-M5-013 an unavailable remote directory remains unknown after a lost acknowledgement',async()=>{const f=fixture();try{await f.run(service=>Effect.gen(function*(){const prepared=yield* service.prepare(f.input,f.context);if(prepared.kind!=='ready')throw Error('prepare');const {host,token}=f.dispatch(prepared.preparation);f.dropAck=true;assert.equal((yield* service.commit(prepared.preparation,host,token,f.context)).kind,'unknown');renameSync(f.remote,f.remote+'-unavailable');assert.equal((yield* service.observe(prepared.preparation,f.context)).kind,'unknown');assert.equal(f.pushes,1);}));}finally{f.cleanup();}});

test("T-M5-011 malformed authority fails before a missing registration preview",async()=>{const f=fixture();try{f.authorized=false;f.authorityValid=false;await f.run(service=>Effect.gen(function*(){const outcome=yield* Effect.either(service.prepare(f.input,f.context));assert.equal(outcome._tag,"Left");if(outcome._tag==="Left")assert.equal(outcome.left.code,"publication-authority-invalid");assert.equal(f.pushes,0);}));}finally{f.cleanup();}});

test('T-M5-011 deferred authority fails closed for ambiguous grants and changed bytes, and waits for unavailable bytes',async()=>{for(const mode of ['ambiguous','wrong','missing'] as const){const f=fixture({deferred:true,...(mode==='ambiguous'?{ambiguous:true}:{hashRead:mode})});try{await f.run(service=>Effect.gen(function*(){const result=yield* Effect.either(service.prepare(f.input,f.context));if(mode==='missing'){assert.equal(result._tag,'Right');if(result._tag==='Right'){assert.equal(result.right.kind,'needs-action');if(result.right.kind==='needs-action'){assert.equal(result.right.authorityRef,null);assert.match(result.right.requiredAuthoritySha256??'',/^[a-f0-9]{64}$/u);}}}else{assert.equal(result._tag,'Left');if(result._tag==='Left')assert.equal(result.left.code,'publication-authority-invalid');}assert.equal(f.pushes,0);assert.equal(git(f.root,'--git-dir',f.remote,'rev-parse','refs/heads/reviewed'),f.base);}));}finally{f.cleanup();}}});
