import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readlink,writeFile,symlink,unlink,readdir,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import {Effect} from 'effect';
import {installPackage} from './pel-install.js';
import {verifyPelPackage} from './pel-package.js';
import {packageFixture} from './fixtures/pel-install/package-fixture.js';
test('T-M6-001 install verifies complete payload and atomically selects an immutable retained build',async()=>{const f=await packageFixture();try{const result=await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}));assert.equal(result.buildId,f.manifest.buildId);assert.equal(await readlink(join(f.prefix,'current')),`versions/${f.manifest.buildId}`);assert.equal(await readlink(join(f.prefix,'bin/foreman')),'../current/runtime/dist/foreman.js');assert.equal((await Effect.runPromise(verifyPelPackage(join(f.prefix,'current')))).manifest.buildId,f.manifest.buildId);assert.equal((await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}))).buildId,f.manifest.buildId);}finally{await f.close();}});
test('T-M6-003 invalid prerequisite and tampered payload preserve the selected installation',async()=>{const f=await packageFixture();try{await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}));const current=await readlink(join(f.prefix,'current')),manifest=await readFile(join(f.prefix,'current/manifest.json'));const old=await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix,nodeVersion:'22.18.0'}).pipe(Effect.either));assert.equal(old._tag,'Left');if(old._tag==='Left')assert.equal(old.left._tag,'InstallPrerequisiteMissing');await writeFile(join(f.sourceRoot,'examples/pel/repair.pel'),'tampered');const changed=await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}).pipe(Effect.either));assert.equal(changed._tag,'Left');if(changed._tag==='Left')assert.equal(changed.left._tag,'PackageIntegrityMismatch');assert.equal(await readlink(join(f.prefix,'current')),current);assert.deepEqual(await readFile(join(f.prefix,'current/manifest.json')),manifest);}finally{await f.close();}});
test('T-M6-003 linked and undeclared package files are rejected before any prefix mutation',async()=>{const f=await packageFixture();try{const path=join(f.sourceRoot,'examples/pel/repair.pel');await unlink(path);await symlink('/etc/passwd',path);const linked=await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}).pipe(Effect.either));assert.equal(linked._tag,'Left');assert.equal((await readdir(f.root)).includes('prefix'),false);}finally{await f.close();}});
test('T-M6-003 staging failure preserves the prior current pointer',async()=>{const f=await packageFixture();try{await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}));const current=await readlink(join(f.prefix,'current'));await writeFile(join(f.sourceRoot,'docs/guides/pel/install.md'),'new valid version');const next=await f.seal('1.0.0');await mkdir(join(f.prefix,'versions',next.buildId));await writeFile(join(f.prefix,'versions',next.buildId,'conflict'),'cannot replace unknown retained content');const failed=await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}).pipe(Effect.either));assert.equal(failed._tag,'Left');assert.equal(await readlink(join(f.prefix,'current')),current);}finally{await f.close();}});

test('T-M6-003 interruption during staging removes partial bytes and preserves current',async()=>{const f=await packageFixture();try{await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}));const before=await readlink(join(f.prefix,'current'));for(let i=0;i<150;i++)await writeFile(join(f.sourceRoot,'examples/pel',`extra-${i}.pel`),'(print 1)\n');await f.seal('1.0.1');const controller=new AbortController();let seen=false;const timer=setInterval(()=>{void readdir(join(f.prefix,'versions')).then(names=>{if(names.some(name=>name.startsWith('.stage-'))){seen=true;controller.abort();}});},1);try{await assert.rejects(Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:f.prefix}),{signal:controller.signal}));}finally{clearInterval(timer);}assert.equal(seen,true);assert.equal(await readlink(join(f.prefix,'current')),before);assert.ok(!(await readdir(join(f.prefix,'versions'))).some(name=>name.startsWith('.stage-')));}finally{await f.close();}});

import {stat} from 'node:fs/promises';
test('T-M6-001 restrictive caller umasks preserve declared installed file modes',async()=>{const f=await packageFixture();const original=process.umask();try{for(const mask of [0o027,0o077]){process.umask(mask);const prefix=join(f.root,`masked-${mask}`);await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix}));const verified=await Effect.runPromise(verifyPelPackage(join(prefix,'current')));for(const file of verified.files)assert.equal((await stat(join(prefix,'current',file.record.path))).mode&0o777,file.record.mode);assert.equal((await stat(join(prefix,'current/manifest.json'))).mode&0o777,0o644);}}finally{process.umask(original);await f.close();}});
test('T-M6-003 a symlink ancestor is invalid input before prefix creation',async()=>{const f=await packageFixture();try{const real=join(f.root,'real'),link=join(f.root,'alias');await mkdir(real);await symlink(real,link);const result=await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:join(link,'new-prefix')}).pipe(Effect.either));assert.equal(result._tag,'Left');if(result._tag==='Left')assert.equal(result.left._tag,'PackageIntegrityMismatch');assert.deepEqual(await readdir(real),[]);}finally{await f.close();}});
test('T-M6-003 a regular-file ancestor is invalid input and leaves its bytes unchanged',async()=>{const f=await packageFixture();try{const file=join(f.root,'not-a-directory');await writeFile(file,'retained file');const result=await Effect.runPromise(installPackage({sourceRoot:f.sourceRoot,prefix:join(file,'foreman')}).pipe(Effect.either));assert.equal(result._tag,'Left');if(result._tag==='Left')assert.equal(result.left._tag,'PackageIntegrityMismatch');assert.equal(await readFile(file,'utf8'),'retained file');}finally{await f.close();}});
