import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtemp,cp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {spawnSync} from 'node:child_process';
import {Effect} from 'effect';
import {sha256Hex} from '@foreman/core';
import {makeLiveRunJournalLayer,type RunId} from '@foreman/event-log';
import {readPelRecords,replayPelRun} from './pel-journal.js';
import {EndstopLedger,makeLiveEndstopLedgerLayer} from './execution-ledger.js';
const profiles=[['gpt-6-astra','codex-app-server'],['gpt-5.6-sol','codex-app-server'],['claude-opus-5','claude-code'],['claude-fable-5-1','claude-code'],['grok-4.6','grok-acp'],['gemini-3.8-flash','gemini-cli']] as const;
async function fixture(fixtureId:string,scenario='approved'){
 const root=await mkdtemp(join(tmpdir(),'pel-model-example-')),assetRoot=join(root,'assets'),stateRoot=join(root,'state');await cp(resolve('packages/orchestration/dist-test/assets'),assetRoot,{recursive:true});await mkdir(stateRoot);const manifest=join(root,'fixture.json');await writeFile(manifest,JSON.stringify({schemaVersion:1,assetRoot,assetManifestSha256:sha256Hex(await readFile(join(assetRoot,'manifest.json'))),fixtures:{responses:[],delivery:{schemaVersion:1,evidenceKind:'test-fixture',fixtureId,temporaryRoot:root,stateRoot,now:Date.now(),scenario,roles:'grok-sol',failurePoint:'none'}}}));
 return {root,stateRoot,invoke:(name:string)=>spawnSync(process.execPath,[resolve('packages/orchestration/dist-test/pel-cli-fixture.js'),'--fixture-manifest',manifest,'run',`examples/pel/${name}`,'--json'],{cwd:root,encoding:'utf8',timeout:30000,maxBuffer:1048576}),ledger:()=>Effect.runPromise(Effect.flatMap(EndstopLedger,p=>p.status('delivery-fixture-contract')).pipe(Effect.provide(makeLiveEndstopLedgerLayer(stateRoot)))),records:(runId:RunId)=>Effect.runPromise(readPelRecords(runId).pipe(Effect.provide(makeLiveRunJournalLayer(stateRoot)))),close:()=>rm(root,{recursive:true,force:true})};
}
for(const scenario of ['approved','gate-failed'])test(`M6 exact conditional.pel captures a candidate before its ${scenario} verification branch`,async()=>{const f=await fixture('m6-conditional',scenario);try{const run=f.invoke('conditional.pel');assert.equal(run.status,scenario==='approved'?0:3,run.stdout+run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.evidenceKind,'test-fixture');assert.equal(result.state,scenario==='approved'?'succeeded':'needs-action');assert.ok(result.candidate.value.commit);assert.equal(result.checks.passed,scenario==='approved');assert.equal(result.review?.verdict??null,scenario==='approved'?'approved':null);const state=await f.ledger();assert.equal(state.counts.implement,1);assert.equal(state.counts.verify,1);assert.equal(state.counts.audit,scenario==='approved'?1:0);assert.equal(state.counts.publish,0);}finally{await f.close();}});
test('M6 exact repair.pel performs its corrected named task call and retains pending delivery milestones',async()=>{const f=await fixture('m6-repair');try{const run=f.invoke('repair.pel');assert.equal(run.status,3,run.stdout+run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.state,'needs-action');assert.equal(result.evidenceKind,'test-fixture');assert.ok(result.candidate.value.commit);const state=await f.ledger();assert.equal(state.counts.implement,1);assert.equal(state.counts.verify,0);assert.equal(state.counts.audit,0);assert.equal(state.counts.publish,0);}finally{await f.close();}});
for(const [profile,transport] of profiles)test(`M6 exact ${profile} example uses its recorded native cell and actual M5 candidate capture`,async()=>{const f=await fixture(`m6-profile-${profile.replaceAll('.','-')}`);try{const run=f.invoke(`profiles/${profile}.pel`);assert.equal(run.status,3,run.stdout+run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.state,'needs-action');assert.equal(result.evidenceKind,'test-fixture');assert.ok(result.candidate.value.commit);const replay=replayPelRun(await f.records(result.runId));assert.ok(replay.ok);if(replay.ok){const completed=replay.value.records.filter(row=>row.type==='pel.effect.observed.v1'&&row.data.externalOutcome==='confirmed-complete'&&row.data.providerIdentity);assert.ok(completed.length>=1);for(const row of completed){if(row.type!=='pel.effect.observed.v1')continue;assert.equal(row.data.providerIdentity?.profileId,profile);assert.equal(row.data.providerIdentity?.transportId,transport);assert.equal(row.data.providerIdentity?.credentialProfileRef,'account:test');}}const state=await f.ledger();assert.equal(state.counts.implement,1);assert.equal(state.counts.verify,0);assert.equal(state.counts.audit,0);assert.equal(state.counts.publish,0);assert.equal(result.usage.observed.inputTokens,10);}finally{await f.close();}});
test('M6 recorded profile fixture rejects another exact model before any action reservation',async()=>{const f=await fixture('m6-profile-grok-4-6');try{const run=f.invoke('profiles/gpt-6-astra.pel');assert.equal(run.status,2,run.stdout+run.stderr);assert.doesNotMatch(run.stderr,/run-started/u);assert.equal((await f.ledger()).counts.totalActions,0);}finally{await f.close();}});
