import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,statSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Effect} from 'effect';
import type {ProviderRequestV1,ProviderIdentityV1,ToolRequestV1} from '@foreman/providers';
import type {HostContextV1} from './pel-run-contract.js';
import {makePelNativePermissionAuthorizer,makePelNativePermissionExecutor} from './pel-native-permissions.js';
function fixture(){const root=mkdtempSync(join(tmpdir(),'pel-native-permission-'));mkdirSync(join(root,'src'));mkdirSync(join(root,'.git'));const info=statSync(root);const context={effect:{effectId:'effect'},workspace:{canonicalRoot:root,directoryIdentity:`${info.dev}:${info.ino}`,grantId:'workspace',writablePaths:['src']}} as unknown as HostContextV1;const request={effectId:'effect',profileId:'gpt-6-astra',transportId:'codex-app-server',credentialProfileRef:'selected',toolPolicy:{mode:'native-coding',workspaceGrantId:'workspace',hostPermissionPortRef:'host',permissionGrantIds:['grant']},limits:{deadline:Date.now()+10000,maxToolCalls:10}} as unknown as ProviderRequestV1;const identity:ProviderIdentityV1={kind:'native',provider:'openai',profileId:'gpt-6-astra',transportId:'codex-app-server',credentialProfileRef:'selected',protocolVersion:'1',sessionId:'s'};return {root,context,request,identity,close:()=>rmSync(root,{recursive:true,force:true})};}
test('native permission authorizer binds each effect, call, arguments, identity and exact grants',async()=>{const f=fixture();try{const tool:ToolRequestV1={callId:'call',name:'item/fileChange/requestApproval',arguments:{path:'src/new.ts'},authorizationBinding:'host'},authorize=makePelNativePermissionAuthorizer(f.request,f.context);const binding=await Effect.runPromise(authorize(f.identity,tool,f.request.toolPolicy));assert.match(binding,/^pel-native-permission-[a-f0-9]{64}$/);assert.equal(await Effect.runPromise(authorize(f.identity,{...tool,authorizationBinding:binding},f.request.toolPolicy)),binding);const executed=await Effect.runPromise(makePelNativePermissionExecutor(f.request,f.context).execute(f.identity,{...tool,authorizationBinding:binding},binding,f.context));assert.deepEqual(executed,{content:{kind:'json',value:{decision:'accept'}},isError:false});for(const change of [{...tool,arguments:{path:'.git/config'}},{...tool,arguments:{path:'/etc/passwd'}},{...tool,name:'arbitrary/tool'},{...tool,authorizationBinding:'forged'}])assert.equal((await Effect.runPromise(authorize(f.identity,change,f.request.toolPolicy).pipe(Effect.either)))._tag,'Left');const changed=makePelNativePermissionAuthorizer({...f.request,effectId:'other'},f.context);assert.equal((await Effect.runPromise(changed(f.identity,tool,f.request.toolPolicy).pipe(Effect.either)))._tag,'Left');}finally{f.close();}});
test('native permission writes require grant paths; read and command cwd stay inside the enforced workspace',async()=>{const f=fixture();try{const request={...f.request,profileId:'grok-4.6',transportId:'grok-acp'} as ProviderRequestV1,identity={...f.identity,provider:'xai',profileId:'grok-4.6',transportId:'grok-acp'} as ProviderIdentityV1,authorize=makePelNativePermissionAuthorizer(request,f.context);for(const [name,args,allowed] of [['edit',{path:'src/a.ts'},true],['edit',{path:'outside.ts'},false],['execute',{command:'node -e "process.exit(0)"',cwd:f.root},true],['execute',{cwd:'/tmp'},false],['read',{path:'outside.ts'},true]] as const){const result=await Effect.runPromise(authorize(identity,{callId:'call',name,arguments:args,authorizationBinding:'host'},request.toolPolicy).pipe(Effect.either));assert.equal(result._tag,allowed?'Right':'Left');}}finally{f.close();}});
test('Codex optional grantRoot is bounded to the original write grant and never authorizes a session grant',async()=>{const f=fixture();try{const authorize=makePelNativePermissionAuthorizer(f.request,f.context);for(const [args,allowed] of [[{},true],[{grantRoot:null},true],[{grantRoot:'src'},true],[{grantRoot:join(f.root,'src')},true],[{grantRoot:f.root},false],[{grantRoot:'/etc'},false],[{grantRoot:'.git'},false],[{grantRoot:'src/../src'},false],[{grantRoot:7},false]] as const){const tool:ToolRequestV1={callId:'grant-root',name:'item/fileChange/requestApproval',arguments:args,authorizationBinding:'host'},result=await Effect.runPromise(authorize(f.identity,tool,f.request.toolPolicy).pipe(Effect.either));assert.equal(result._tag,allowed?'Right':'Left',JSON.stringify(args));if(result._tag==='Right'){const output=await Effect.runPromise(makePelNativePermissionExecutor(f.request,f.context).execute(f.identity,{...tool,authorizationBinding:result.right},result.right,f.context));assert.deepEqual(output.content,{kind:'json',value:{decision:'accept'}});}}}finally{f.close();}});
